### ISSUE TITLE
How do I go back to parent directory when I `Enter` on a directory or a file?

### ISSUE THREAD

**Issue by c02y** [tramhao/termusic#10]
When I use `Enter` to enter a directory or on a file, it seems I cannot go back to the previous level
1. when I `Enter` on a directory, it will enter this directory 
2. when I `Enter` on a file, the structure will only contain this file

I cannot go back to the previous state/directory.

**Comment by tramhao** [comment]
Backspace can go back to parent dir.

**Comment by c02y** [comment]
Yeah, the `Enter` and `Backspace` should be put into `C-h` page.
