### ISSUE TITLE
[Bug] Windows, volume doesn't apply

### ISSUE THREAD

**Issue by Jakobohrnell** [tramhao/termusic#105]
When I start a new track, it doesn't apply my set volume and instead plays it at full blast. If I adjust the volume, it will however apply that new value.

So, play new track > starts playing at max volume even though it says Volume: 10 > adjust volume to 15 > track now plays at volume 15.

It does appear to properly apply the volume if I let it naturally move to the next track however, instead of doing so manually using the default keybind "l" in the playlist widget.

**Comment by tramhao** [comment]
This should be a bug. As when I add podcast, the player was adjusted to play http file. Let me fix it. And before that, mpv backend should work.

**Comment by tramhao** [comment]
Should be fixed in v0.7.11.
