### ISSUE TITLE
Panic after start: cannot get audio dir

### ISSUE THREAD

**Issue by proycon** [tramhao/termusic#106]
Immediately after installing and launching termusic, it panics:

```
thread 'main' panicked at 'cannot get audio dir.', src/config/mod.rs:48:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This was the first launch so I indeed have no `~/.config/termusic/config.toml` yet, nor is it clear from the instructions how to create one ( and `--help` doesn't work because of the panic).

**Comment by proycon** [comment]
After some investigation I though the cause was an unset `$XDG_MUSIC_DIR`, but even setting that doesn't help.

**Comment by proycon** [comment]
It seems to work now after setting all the `XDG_*` environment variables in my shell configuration.

**Comment by tramhao** [comment]
My bad, I didn't handle the error when audio dir is not set. Before I use ~/Music but seems it's not portable and ppl met problems in win and mac. Now I use audio dir but I should set default value when it's not set. I'll fix it in new release.

**Comment by 154pinkchairs** [comment]
@tramhao maybe handle this like it is handled with [gonk](https://github.com/zX3no/gonk), so that multiple dirs can be added

**Comment by tramhao** [comment]
v0.7.9 released and will not panic.
