### ISSUE TITLE
mp3 directory created into ~/Music for no reason

### ISSUE THREAD

**Issue by Porkepix** [tramhao/termusic#109]
I recently noticed that an empty `mp3` directory is created in `~/Music` by termusic. Even when deleting it, on next launch it'll be created again. For this and another issue I'm about to create, is there some way to have a debug mode with logs to check out what could cause this creation?

**Comment by tramhao** [comment]
This directory comes from default configuration. In order to demonstrate how to define multiple roots, I set ~/Music and ~/Music/mp3 as two defaults roots. In below code:
```rust
let mut path = dirs::audio_dir().expect("cannot get audio dir.");
        path.push("mp3");
        if !path.exists() {
            std::fs::create_dir_all(path.as_path()).unwrap_or_else(|_| {
                panic!(
                    "create music dir failed: {}",
                    path.as_path().to_string_lossy()
                )
            });
        }
```

This directory was created. Please suggest what behavior is more acceptable. Thanks.

**Comment by Porkepix** [comment]
Well, I don't expect the player to create its own directory (except maybe for those than reorder all your library and organize things their way, but I was never fond of these behavior, personal preference though).

Shouldn't the player just read it if it exists and nothing more? (On top of that, it's created on both of my computers, including the one that doesn't have `~/Music/mp3` in its `music_dir`).

**Comment by tramhao** [comment]
Let me think about how to solve this. The main reason to provide it, is to demonstrate the change root function.  There should be a way to do it.

**Comment by Porkepix** [comment]
> Let me think about how to solve this. The main reason to provide it, is to demonstrate the change root function. There should be a way to do it.

I don't understand what you mean by "demonstrate the change root function" here? Demonstrating a feature shouldn't create empty dir just for the sake of showing something, I think?

**Comment by MahouShoujoMivutilde** [comment]
> This directory was created. Please suggest what behavior is more acceptable. Thanks.

Don't create directory, just let the user know that such and such directories from "Root Music Directory" option are in fact don't exist, and they should either remove them from the config or create them.

Also, on related note: 

I have root path set to a completely different path, without ~/Music/mp3 there at all, yet it still creates it on every launch.

**Comment by tramhao** [comment]
v0.7.9 released and will not create music_dir.

**Comment by MahouShoujoMivutilde** [comment]
Nice, thank you!
