### ISSUE TITLE
After downloading music using `s` feature, termusic will merge lrc file into the downloaded music file

### ISSUE THREAD

**Issue by c02y** [tramhao/termusic#11]
![Peek 2021-09-24 23-49](https://user-images.githubusercontent.com/2135996/134704243-1248b1b3-137e-4bcb-b657-ada04466adf7.gif)

The lyric has nothing to do with the music file, the lyric file will be merged into the downloaded file, the lyric file which is for another music file is gone now.

**Comment by tramhao** [comment]
should be fixed. Thanks for the feedback.

**Comment by tramhao** [comment]
Fixed in d56a21f8363f5c63a3b8f4cfac9aa1ba04fdab4d and 253bce923997b98accf24bb0c3fc59237a5d29a2.
