### ISSUE TITLE
Unable to install using `cargo install` with error: "failed to select a version for the requirement `lofty = "^0.10"`"

### ISSUE THREAD

**Issue by Bradshaw** [tramhao/termusic#111]
# Problem

Trying to install termusic with the `cargo install termusic` command fails with the following error:
```
gaeel@doppelganger ~> cargo install termusic
    Updating crates.io index
  Installing termusic v0.7.8
error: failed to compile `termusic v0.7.8`, intermediate artifacts can be found at `/tmp/cargo-installS0LOZH`

Caused by:
  failed to select a version for the requirement `lofty = "^0.10"`
  candidate versions found which didn't match: 0.11.0, 0.9.0, 0.8.1, ...
  location searched: crates.io index
  required by package `termusic v0.7.8
```

This problem doesn't occur when building from source with `git checkout v0.7.8 && cargo build --release`. Building from source runs to completion and produces a working executable.

# Context

Running on Fedora 36 in a podman container inside Fedora Silverblue 37.20230130.0.
Rust toolchain is up to date at 1.67.0:
```
gaeel@doppelganger ~> rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /var/home/gaeel/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.67.0 (fc594f156 2023-01-24)
```

**Comment by Kurtsley** [comment]
Bumping the version to 0.11.0 seems to fix this on my end.

**Comment by tramhao** [comment]
seems lofty author cancelled version 0.10 for some reason. Please use 0.11 or 0.9

**Comment by tramhao** [comment]
The author of lofty is so nice to submit a pull request for updating version. This should be ok.

**Comment by Bradshaw** [comment]
I'm not the author of lofty, just someone who uses termusic as their main music player ;)
