### ISSUE TITLE
Missing shared library

### ISSUE THREAD

**Issue by FlanOfHarmony** [tramhao/termusic#117]
I tried to install the latest dev version on Fedora since I cannot launch termusic because of [this issue](https://github.com/tramhao/termusic/issues/114) on 0.7.9, but I still cannot launch as I’m now getting the `termusic: error while loading shared libraries: libsixel.so.1: cannot open shared object file: No such file or directory` error. I looked it up quickly but I’m not really sure if this is a missing dependency and how am I supposed to install it.

I took a look at the commit history, I can install and launch termusic when using [this commit](https://github.com/tramhao/termusic/commit/11c045266c2c5a84185c69dc123ea334fdea51fa).

**Comment by tramhao** [comment]
Sorry for the problem caused. In dev branch, I am trying ueberzugpp because it support sixel for displaying album cover. Still working on it as some problems under wayland.

For the original issue, you can setup XDG_AUDIO_DIR in your profile to solve it.

**Comment by FlanOfHarmony** [comment]
Ok!
