### ISSUE TITLE
Information of another song is displayed while listening to another

### ISSUE THREAD

**Issue by CRAG666** [tramhao/termusic#120]
I love this player, but since I've been using it I've had this problem, I thought that in later versions it would be solved.
The problem is that sometimes I select a song and the information shown is different, that also happens with the covers of the songs.
Another rather annoying behavior is that on some occasions I can't exit termusic and I have to close the terminal completely, it stays locked, I can't access anything, nor move or exit.

**Comment by tramhao** [comment]
Thanks so much for the feedback. The displayed cover and song info is the current song being played. If it's not the same, there must be something wrong with playlist handling. 
When exit, I could think of a mpris feature that lead to fail to exit.  Would you please check if with mpris compiled, it'll be ok? You can build with cargo build --release.

**Comment by CRAG666** [comment]
I use this to install it on arch linux, I don't know if I need to add something else for the
![Screenshot from 2023-04-11 at 13_58_19 185707595](https://user-images.githubusercontent.com/34254373/231275100-dbc9c644-9c05-44c8-8b7c-48f56587a0ab.png)

**Comment by CRAG666** [comment]
The problem occurs when a song is supposedly corrupt, but I did a test with the flac command and all the songs seem to be fine. to exit I have to kill the process, this would not be a problem; but then termusic does not open

**Comment by CRAG666** [comment]
Fortunately, I was able to reproduce the error now and it is not mpris. On the other hand the error still occurs. In the video, select a song that does have a cover and that is not corrupt, however, the correct cover is not visible (in fact, nothing is visible), apart from that, termusic also gets stuck, making it impossible to move or perform any action, the only way to close it is with kill, but when trying to open it again, termusic will not open, to make the video short I killed it immediately, but it has managed to open after hours of waiting.
@tramhao thaks
https://user-images.githubusercontent.com/34254373/231600305-3bb1e857-c161-4414-b2f8-3ea9ddd021e0.mp4

**Comment by tramhao** [comment]
I met the problem of cannot exit and have to kill. I'm in the process of debugging adjust lyric function. As this function is related to the modification of track being played, I'm thinking that it might be the handling of current song in playlist. I'll first convert the player into a background thread, and see if this helps.

**Comment by tramhao** [comment]
> 

You're using which terminal emulator? Seems relate to ueberzug.

**Comment by CRAG666** [comment]
use kitty as terminal, In fact, I also tried compiling without that functionality and the error keeps happening, I don't know if it's related to the fact that I have more than 1000 songs in my playlist

**Comment by tramhao** [comment]
Please try if e2812faa103a1fba21fc3d26769e0b0ff5c383ac is working with your situation. Thanks.

**Comment by CRAG666** [comment]
@tramhao Does that commit also fix the freezing problem?

**Comment by tramhao** [comment]
I think it should fix the freezing problem.
