### ISSUE TITLE
Application crash caused by thumbnail fillup in /tmp

### ISSUE THREAD

**Issue by FlanOfHarmony** [tramhao/termusic#122]
So for a while and from quite a few versions, I’ve been having weird crashes where termusic stops responding and takes all of the allocated core, and killing it with something like `top` and then reopening wouldn’t be of any help, only rebooting. I was having having a hard time reproducing the issue so that’s why I didn’t open a ticket earlier, but today miraculously before termusic stopped answering it printed me a message indicating an issue: something about no more filenames available in `/tmp`. Then termusic stopped responding. Upon opening `/tmp`, I realized that it was filled with `.tmp.viuer.X` where X would take the numbers `0` to  `9`, the letters `a` to `z` and `A` to `Z`. After deleting all these files, I am now able to launch `termusic` without rebooting my pc.

This makes sense because `/tmp` is cleared when powering off. In my music collection, many albums have not only a file like `cover.jpg` in the album folder, but also a thumbnail within each music file track. I can now reproduce the issue : if I play successively 26+26+10 tracks that have thumbnails, or even play 26+26+10 times the same track with a thumbnail, `/tmp` slowly fills up for each track played until no more of these filenames are available and the application stops answering and cannot be relaunched without deleting them.

**Comment by FlanOfHarmony** [comment]
[Sigh] I just read the issue tracker, and this is a duplicate of #92 . I’m therefore closing this.

**Comment by tramhao** [comment]
I take some code from spotify player to fix the problem. Please try if it's working. Thanks.

**Comment by tramhao** [comment]
Please checkout master branch.

**Comment by FlanOfHarmony** [comment]
Yep, your comment fixes it!

**Comment by tramhao** [comment]
Fixed and released in v0.7.11.
