### ISSUE TITLE
Network streams?

### ISSUE THREAD

**Issue by 097115** [tramhao/termusic#123]
It's probably a bit unusual ask but... Given that `GStreamer` and `mpv` backends already support opening network resources, would it be possible to add playing network streams, like internet radio stations, to `termusic`? We could store those in `m3u` files in the music directory, just like ordinary files:

    #EXTM3U 
    #EXTINF:-1,Klassik Radio Opera
    http://klassikr.streamabc.net/klr-opera-mp3-192-1730403

What do you think?

Or may be it's already possible? I just can't see how to switch backends...

Thank you.

**Comment by tramhao** [comment]
currently I'm changing the player to a separate process, so that it can support internet audio. Right now if you want, you can try:
make gst && make post 
or:
make mpv && make post
This way you can use gst or mpv backend. They support internet url.

**Comment by 097115** [comment]
Thanks for the reply!

> Right now if you want, you can try: `make gst && make post`

I did this (`cargo build --no-default-features --features mpris,gst --release --all`), but it still doesn't open an M3U file with a network resource (like the one quoted above) and tries to download a link if I provide an URL via the `s` hotkey.

> currently I'm changing the player to a separate process

Then, may be it's better to just wait for the update? :)

Anyway, thanks again for the support!

**Comment by tramhao** [comment]
I just tried and found that it doesn't work.  I'll keep this in mind and figure out a way to handle this radio format.

**Comment by tramhao** [comment]
In dev branch, the commit a3c5 can load m3u of network audio. However, I cannot get the duration of this stream correctly.  I don't know if this is correct.

**Comment by 097115** [comment]
Thanks, interesting!

Tried to build but got a bit of errors, though: [gst backend](https://0x0.st/HQD7.txt), [mpv backend](https://0x0.st/HQDR.txt)

**Comment by 097115** [comment]
BTW, speaking about the duration of the stream... I think time related characteristics available via a stream, are a) elapsed time and b) elapsed time + cached time (with the latter being an equivalent to the total time for usual files). Both of these keep changing (growing) constantly.

**Comment by tramhao** [comment]
Sorry I forgot to mention, the dev branch currently only works with symphonia backend.  Just make and make full.

**Comment by 097115** [comment]
Thanks! :)

So, I build it (via GitHub, don't have Rust installed locally) with `sudo apt-get install libasound2-dev libdbus-1-dev protobuf-compiler` and `cargo build --release --all`, but then it just fails with 

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-utils-0.7.0/src/utils.rs:69:17

Probably, will just wait for a release :)

Of course, thanks for your interest and support!

(Just in case, the `protobuf-compiler` package was added because of [this error](https://0x0.st/HQdP.txt) I got when building.)

**Comment by tramhao** [comment]
I think your build is successful. The error is termusic-server is not found. You need to copy it into your PATH. Thanks.

**Comment by tramhao** [comment]
By the way, I updated dev branch and gstreamer,mpv can build now.  When using mpv backend, the behavior of duration is like your description, it will show the cached time and elapsed time. Thanks so much for the hint.

**Comment by 097115** [comment]
> I think your build is successful. The error is termusic-server is not found. You need to copy it into your PATH. Thanks.

Ah, indeed you were right! So I tested it a bit, looks very nice, thank you :)
