### ISSUE TITLE
Left and Right Channels are inverted

### ISSUE THREAD

**Issue by FlanOfHarmony** [tramhao/termusic#124]
I can’t believe it took me this long to realize this but it seems that the left (L) and right (R) channels for stereo audio are inverted.... I played a file with a few video players other than termusic and also checked on youtube, and termusic is the only player playing my audio file with the right and left inverted.

**Comment by tramhao** [comment]
Probably related to

https://github.com/RustAudio/rodio/pull/455/files#diff-ecef08a633c3f06f5e38c52de68d6a04e42596445544e8e12f843aa4d277bb02

**Comment by tramhao** [comment]
I merged upstream fix and it should be ok now. Released in v0.7.11.
