### ISSUE TITLE
[Bug] Ignores configuration and resets it back.

### ISSUE THREAD

**Issue by xplshn** [tramhao/termusic#125]
Whenever I replace the colors mentioned on the CFG, or delete the alacritty part of it. It gets replaced by the original one

**Comment by tramhao** [comment]
All options can be configured in config editor. For the themes, you can also edit theme files. Basically there is no need to edit config.toml.  The values will be restored to default if one field is missing. You can edit the config, but need to keep all fields.

**Comment by tramhao** [comment]
It's not a bug. If you want to edit, please edit the files inside ~/.config/termusic/themes . Please don't delete alacritty part. For any fields if it's missing, the whole config file will be restored to default.
