### ISSUE TITLE
[bug] Volume goes 100 when next song started

### ISSUE THREAD

**Issue by Liferenko** [tramhao/termusic#128]
So the title told it. Next song goes 100% volume when previous one was playing 5-10%.
I can't say it bother a lot for now but it might be kinda "McCalley Culkin + guitar in Michael Jackson's video" moment for somebody :) 

I'll try to fix it myself and push PR asap.

---
[just in case] Device info:
mac M1
Darwin MacBook-Air-MacBook.local 22.4.0 Darwin Kernel Version 22.4.0
root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64

**Comment by tramhao** [comment]
It's very strange. The music volume will be set inside rusty_backend/mod.rs . Currently it's set when start and stop. But for mac, I don't have experience so your help is very appreciated.

**Comment by tramhao** [comment]
I just pushed a fix in master branch. I found that the volume changed is not preserved in the player loop. Thanks so much  for reporting.

The difference between next and play selected is that in gapless mode, next track will not stop the sink, thus the volume is preserved.

**Comment by Liferenko** [comment]
yep, it works perfect with this fix. Thank you
