### ISSUE TITLE
List of supported audio formats?

### ISSUE THREAD

**Issue by neruthes** [tramhao/termusic#13]
![image](https://user-images.githubusercontent.com/2139261/134799988-2d76d0ce-a58d-4f57-8ba7-cae16c12b6ce.png)

Cannot play WAV audio files. Is this program designed to exclude WAV or I am encountering a bug or a dependency shortage?

**Comment by tramhao** [comment]
Should be playable but metadata is not handled. Currently support mp3/m4a/flac/ogg .

**Comment by tramhao** [comment]
I just checked that wav file can work with id3 tags so it's not hard to implement. Do you use wav files often? Thanks.

**Comment by tramhao** [comment]
implenented in 8ecd28a4fc2f94ec27ad5c1a3862b75569bfdd53.

**Comment by tramhao** [comment]
upgrade to v0.3.14 should be all right.

**Comment by neruthes** [comment]
Great. Thank you.

**Comment by neruthes** [comment]
![image](https://user-images.githubusercontent.com/2139261/134917444-1b7d8ff9-6637-44fb-91f4-7e860101a965.png)

Working well.
