### ISSUE TITLE
installation Error

### ISSUE THREAD

**Issue by MicroBlueee** [tramhao/termusic#133]
![image](https://github.com/tramhao/termusic/assets/49147382/6f62aaea-befc-4859-bb79-66387f4ce034)

**Comment by tramhao** [comment]
It's a new required package. In arch, it's called protobuf.

**Comment by MicroBlueee** [comment]
My platform is Mac with Intel chip. Can you help me about some details on Mac?

**Comment by tramhao** [comment]
For mac, you can use this: `brew install protobuf`

**Comment by MicroBlueee** [comment]
Many thanks, solved
