### ISSUE TITLE
No track is playing. Stopped.

### ISSUE THREAD

**Issue by rkochar** [tramhao/termusic#135]
<img width="1011" alt="image" src="https://github.com/tramhao/termusic/assets/44548936/28cd87c6-05f1-4c87-9651-b1312b9ed8a1">

I just installed termusic on a M2 (macOS 13.4.1) with cargo and protobuf (v23.4) with brew. Played the first song (all in m4a) and then termusic semi-froze. I can still toggle things but can not play anything. This could be a problem with termusic but also something with hardware/audio. Closing and restarting termusic and force quitting the terminal and re-opening did not help. However I noticed that the first song is still there in playlist. Is there a flush or force reset or delete cache? That can probably solve this, otherwise, what other information can be helpful to debug? (Is there a log file or something like that? Could you please add that to the contributing md file).

There is no problem playing the same song with Music (default player in Macbook) so the file is not corrupted. Using `n` and `l` do play a different song do not work either.

**Comment by tramhao** [comment]
Firstly you can check ~/.config/termusic/playlist.log,and see if this file is empty. If it's empty, you can paste several file path into it, or use termusic to add some files into the playlist.
Secondly, you can run termusic-server with: 
RUST_LOG=trace termusic-server
this way you can figure out what's the problem when playing. 
Seems to me it's related to alsa or cpal.

**Comment by rkochar** [comment]
This was not working and the rust_log did not make sense to me. Downloaded termusic again and it seems to be working fine now. Thanks.
