### ISSUE TITLE
How do I play a music?

### ISSUE THREAD

**Issue by hs02uly** [tramhao/termusic#139]
How do I play a music?
I used ctrl+h to look at help, but I couldn't figure it out...
Sorry to ask such a stupid question...😭

**Comment by ScratchCat458** [comment]
The default button to play a song is `l`. To play a folder of songs use `SHIFT+L`.

**Comment by tramhao** [comment]
Basically to play a song, just add the song to playlist. Closing this  because of 397aed0fdee21a85628ef00cd7b3fe69a27a62d1
