### ISSUE TITLE
mpris default

### ISSUE THREAD

**Issue by 0323pin** [tramhao/termusic#14]
Hi,

NetBSD package maintainer here.
Just saw your latest release, thanks.

Although, personaly I have `dbus` installed on my system, I know a lot of people on *BSD are opposed to its use.

Having `mpris` as default and forcing `dbus` will for sure make some people back-off from using `termusic`.
This is obviously, your call as you are the developer. I will include the `dbus` dependency on my next update but, thought I'd just let you know the fact.

Best Regards,
pin

**Comment by tramhao** [comment]
Sorry for the change. I'll change it back in v0.3.15. Please ignore
v0.3.14. I think today I can do it. Thanks.

**Comment by 0323pin** [comment]
@tramhao No problem, thank you for your understanding. We are currently cutting the Q3 stable branch and commits are not allowed anyway, so I'll commit 0.3.15 once commits are open again.

**Comment by 0323pin** [comment]
Thanks.

**Comment by 0323pin** [comment]
v0.3.15 merged. The stable branch will ship with v0.3.13.
