### ISSUE TITLE
Aur Package lto issue

### ISSUE THREAD

**Issue by LuisB79** [tramhao/termusic#149]
You need to disable lto at PKGBUILD to compile properly the program, if not an error will occur. Please add '!lto' into options array

**Comment by LuisB79** [comment]
And i'm getting that some packages are from 2021, not sure if newer versions are available

**Comment by hasezoey** [comment]
i just tried compiling latest master(50e64f07e152df1f7ceb04f208b2f4f5ea659f04) with LTO, which seems to compile and run just fine.

also i dont know if the owner of this package is the same one publishing the AUR; also please be more specific which AUR package you use (there is [`termusic`](https://aur.archlinux.org/packages/termusic) and [`termusic-git`](https://aur.archlinux.org/packages/termusic-git))

**Comment by LuisB79** [comment]
> i just tried compiling latest master([50e64f0](https://github.com/tramhao/termusic/commit/50e64f07e152df1f7ceb04f208b2f4f5ea659f04)) with LTO, which seems to compile and run just fine.
> 
> also i dont know if the owner of this package is the same one publishing the AUR; also please be more specific which AUR package you use (there is [`termusic`](https://aur.archlinux.org/packages/termusic) and [`termusic-git`](https://aur.archlinux.org/packages/termusic-git))

Do you have lto in makepkg.conf enabled by default?, the issue is when you have it, and lto in the rust compile options, and most arch based distros have lto enabled by default, also termusic-git

**Comment by hasezoey** [comment]
> Do you have lto in makepkg.conf enabled by default?, the issue is when you have it, and lto in the rust compile options, and most arch based distros have lto enabled by default, also termusic-git

i have not tried the aur package, i had tried the latest git and compiled with cargo directly (after adding the LTO profile option); i do not know enough where the LTO option from the PKGBUILD would be otherwise applied, that is why i asked if this is resolved now.
(Note i have tried ld and lld)

**Comment by LuisB79** [comment]
> > Do you have lto in makepkg.conf enabled by default?, the issue is when you have it, and lto in the rust compile options, and most arch based distros have lto enabled by default, also termusic-git
> 
> i have not tried the aur package, i had tried the latest git and compiled with cargo directly (after adding the LTO profile option); i do not know enough where the LTO option from the PKGBUILD would be otherwise applied, that is why i asked if this is resolved now. (Note i have tried ld and lld)

yes, i've tried the same approach with other rust programs, see https://github.com/woelper/oculante/issues/191, and it works, tbh its prolly a bug in makepkg or something, i doubt it's resolved, and well one would like to install from aur instead of recompiling each update directly in cargo

**Comment by hasezoey** [comment]
just for testing (and because i could), i tested [`termusic-git`](https://aur.archlinux.org/packages/termusic-git) without the `!lto` option, and it just compiled (and runs) just fine (after removing `uberzug`, as i didnt want it installed and it not being available in the repos (not aur))

diff:
```diff
diff --git a/PKGBUILD b/PKGBUILD
index f69bbc6..fb46cce 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -7,12 +7,11 @@ pkgdesc='Music Player TUI written in Rust'
 arch=(x86_64)
 url=https://github.com/tramhao/termusic
 license=(GPL3 MIT)
-depends=(dbus gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gstreamer mpv protobuf ueberzug) # alsa-lib libmpv.so
+depends=(dbus gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gstreamer mpv protobuf) # alsa-lib libmpv.so
 makedepends=(cargo git)
 optdepends=('ffmpeg: extract audio by downloader' 'yt-dlp: download files')
 provides=("${pkgname%-git}")
 conflicts=("${pkgname%-git}")
-options=(!lto)
 source=("$pkgname::git+$url.git")
 sha256sums=(SKIP)
```

if the problem still persists for you, please explain more where it fails and what the error is and what your system is

**Comment by hasezoey** [comment]
@Porkepix 50e64f0 is about a month old now, could you try some newer version?
also just to confirm, you have the sqlite dev-dependencies installed?

could you provide `ld --version`?
if you want to try, could you also test running cargo build / cargo run manually instead of through the script with LTO enabled?

PS: also please note that i too am not am linking expert

**Comment by hasezoey** [comment]
> As for running this manually fro cargo, I tried various ways but couldn't find one that was acting the same way (messages about experimental features and so on), nor could I find good documentation on the good way to do this.

i dont quite know what this would be referencing.

the simplest build i can imagine with rust's lto (assuming you have rust and the build dependencies installed):
```sh
git clone https://github.com/tramhao/termusic.git --depth 10
cd termusic
# enable LTO (to my understanding)
sed -i -- "s/# lto = true/lto = true/" Cargo.toml
cargo build --release
# verify all binaries exist
ls -al target/release/{termusic,termusic-server}
```

i dont know what the `lto` option in `PKGBUILD` sets, but i can reproduce the error (unlike https://github.com/tramhao/termusic/issues/149#issuecomment-1944544321, i think somehow lto is not a default option at least on my system):

```sh
git clone https://aur.archlinux.org/termusic-git.git
cd termusic-git
# remove that dependency, as it does not exist for me
sed -i -- "s/ueberzug//" PKGBUILD
# explicitly enable lto
sed -i -- "s/options=(\!lto)/options=(lto)/" PKGBUILD
makepkg
```

but i dont know how to fix it, the best i could come up with if wanting to have *some* lto is to use the lto option in the cargo file:

```sh
git clone https://aur.archlinux.org/termusic-git.git
cd termusic-git
# remove that dependency, as it does not exist for me
sed -i -- "s/ueberzug//" PKGBUILD
# get source
makepkg -o
# enable rust's lto
sed -i -- "s/# lto = true/lto = true/" src/termusic-git/Cargo.toml
# build without resetting source (and so not undoing the sed)
makepkg -e
```

**Comment by tramhao** [comment]
> i just tried compiling latest master([50e64f0](https://github.com/tramhao/termusic/commit/50e64f07e152df1f7ceb04f208b2f4f5ea659f04)) with LTO, which seems to compile and run just fine.
> 
> also i dont know if the owner of this package is the same one publishing the AUR; also please be more specific which AUR package you use (there is [`termusic`](https://aur.archlinux.org/packages/termusic) and [`termusic-git`](https://aur.archlinux.org/packages/termusic-git))

I'm not the maintainer of arch packages.

**Comment by hasezoey** [comment]
> When I was looking for ways to have lto directly from command line to reproduce the issue with only cargo, I found out something about like two "levels" of lto, maybe the one from makepkg is trying to have a more "pushed" ones, resulting in this issue?

if you mean `fat` and `thin`, i have tried both, resulting in the same error

**Comment by hasezoey** [comment]
@Porkepix 

It looks like the user was deleted, so maybe it was automatic?

In any case, termusic does not maintain the [termusic arch linux package](https://archlinux.org/packages/extra/x86_64/termusic/) nor the [termusic-git aur package](https://aur.archlinux.org/packages/termusic-git), so discussion should likely either happen there or be moved to a [discussion](https://github.com/tramhao/termusic/discussions).

**Comment by hasezoey** [comment]
> It looks curious, I don't see why a user removal of an account that's not the author should close the issue, even less rename the title to a dash…?

I dont know what github will do, though from what i can tell, it was the author that got deleted? (at least the original comment shows as `ghost` too)

> But from what I understand from your own comment in https://github.com/tramhao/termusic/issues/149#issuecomment-1986877781 you reproduced the issue yourself?

Yes i could reproduce the issue when building with a makepkg file and arch's lto, but i dont know enough to fix it and rust's own lto works just fine from my testing.

Also btw https://github.com/tramhao/termusic/issues/149#issuecomment-1986877781 was about having tried changing the lto options in rust while arch's lto was also enabled to see if there was a issue with a specific kind (`fat` / `thin`), but both resulted in the same error.

**Comment by hasezoey** [comment]
> Could this still be reopened then and at the very least set the title back to something that have a meaning? (I find it absurd they remove the title if we can still read every message in it…)

I agree with changing the title back, but i do not have the power to do so (dont have Triage or Write permissions).

@tramhao could you change it back?

> I believe they moved to a closed platform where I'm not, though

Likely depends on where you wanna file the issue, IIRC they have a Zulip where you could ask.

**Comment by hasezoey** [comment]
> Didn't they (unfortunately) move to Discord? I looked at this Zulip and have no idea where that would be asking, I'm not used to this.

I guess i missed them creating a discord, though from what i can see `Zulip` is still a active chat platform (see https://www.rust-lang.org/community)
