### ISSUE TITLE
What does "Queue" mean

### ISSUE THREAD

**Issue by neruthes** [tramhao/termusic#15]
## Introduction

I happened to notice that, a track does not vanish from the "Queue" after it is finished. In other words, the "Queue" does not "consume" tracks.

This is counterintuitive (at least for me). As we work with the concept "Queue", we usually expect its contents to be temporary (volatile). We suppose that a message queue consumes messages sent to it. A queue should be like a character device.

## The Language

From the perspective of language, the "playlist" should be named "library", while the "queue" should be named "playlist". I can sense a misplacement here.

## The Feature

From the perspective of feature, it will be good to control the *mode* of the list ("queue") like:

Mode Name | Description
--- | ---
Queue Mode | Tracks are consumed after finishing.
Loop Mode | The cursor moves down the list and moves back to the first one after finishing the last one.
Single Loop Mode | The player keeps playing the same track; the cursor stays.

Keyboard shortcuts `Alt+Q`, `Alt+L`, and `Alt+S` may be good for choosing modes. Additionally, using `m` to switch through modes will also be good.

## The Metaphor

All music playing softwares and hardwares date back to the time of tapes. We learned the ideas of Play/Pause, Seek, and Loop since the tape era.

This proposes the question: Who moves? Does the queue move, or does the cursor move?

Traditional music player softwares (e.g. iTunes) tend to keep a static playlist while allowing the cursor to move down the list as the player plays.

## Random Personal Nonsense

The entire "queue" thing is useless for me. I always play entire albums from the beginning to the end. While I know that a lot of people are not like me, I still want to minimize the impact of the existence of the "queue" things when I look for music player softwares.

## Conclusion

- Feature Request: Mode switching in the playlist (currently named "queue"): Queue, Loop, Single Loop.
- Feature Request: Indicator for the current track in both the library (currently named "playlist") and the playlist (currently named "queue").

P.S. I will appreciate if you may reconsider the naming of the components, and will always respect your choice.

**Comment by tramhao** [comment]
yed I just added a consume mode yesterday and will release in 0.3.16.

**Comment by tramhao** [comment]
single loop is like loop mode,but only one song in queue. Is that working for you?

**Comment by neruthes** [comment]
> yes I just added a consume mode yesterday and will release in 0.3.16.

Glad to hear that!


> single loop is like loop mode,but only one song in queue. Is that working for you?

This should be good enough for me and other people.

**Comment by tramhao** [comment]
Thanks so much for your explanation of the queue and it helps me a lot:) . I'll implement the three modes accordingly. Also I've renamed the names of playlist and queue to library and playlist. 
There is one question though:
when switching with key m, which order will be natural? And generally speaking, which mode should be default? Thanks.

**Comment by tramhao** [comment]
Would you please clone e40061162dcbb4739eb26d2fb8b041cafc5614ac to see if it's all right? Probably some little bugs still exists for single loop or queue mode. Thanks!

**Comment by tramhao** [comment]
About hotkey, I only added m key as a switch. It seems too much keys already.

**Comment by neruthes** [comment]
> There is one question though: when switching with key m, which order will be natural? 

I think Queue / Look / Single Loop will be a good order. This is the default for iTunes and subsequently iOS Music app. In my memory, this is the common practice, although I did not use many music apps recently.

> And generally speaking, which mode should be default? Thanks.

A humble opinion, Queue mode may the the default.

> Would you please clone e400611 to see if it's all right? Probably some little bugs still exists for single loop or queue mode. Thanks!

I am not very familiar with Rust and Cargo, but I would like to try. I will come back later if things get right.

> About hotkey, I only added m key as a switch. It seems too much keys already.

Yes. A single hotkey for switching should be enough. There can be more features in the future and they will occupy more keys.

**Comment by neruthes** [comment]
I have tried out the latest public version (0.3.16). Things are working well. Great.
