### ISSUE TITLE
Show volume level

### ISSUE THREAD

**Issue by orhun** [tramhao/termusic#16]
I don't know the inner workings of the sound implementation but is it possible to show the volume level on the interface? I think seeing that would be pretty helpful.

(I apologize if it is already being shown and I missed it.)

**Comment by tramhao** [comment]
not yet. I don"t know which place to show it. Have a recommendation?

**Comment by tramhao** [comment]
I added the function. Volume is displayed in the title of progress bar. Please kindly check:
d2db9621922f54e64065dd0c2a2ad733592cdcd0
