### ISSUE TITLE
Adding folder that has subfolder does not work for songs in subfolder

### ISSUE THREAD

**Issue by hasezoey** [tramhao/termusic#164]
Currently `SHIFT+L` only adds songs of the currently selected directory, not any of the sub-directories songs, see example (Actions are executed on the mentioned directories):

```txt
Music // Action "SHIFT+L" adds nothing
└── Artist // Action "SHIFT+L" only adds "song2.mp3"
    ├── Album // Action "SHIFT+L" adds "song1.mp3"
    │   └── song1.mp3
    └── song2.mp3
```

**Comment by tramhao** [comment]
Yes, the adding is not recursive. Maybe we should provide a method to add recursively.

**Comment by storopoli** [comment]
> Yes, the adding is not recursive. Maybe we should provide a method to add recursively.

Maybe Ctrl+Shift+L to add all recursive?

**Comment by hasezoey** [comment]
if it should ever be recursive, how should links (type directory) be handled, which could potentially be circular?

**Comment by hasezoey** [comment]
Duplicate of #103
