### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by tramhao** [tramhao/termusic#170]
I made a mistake today. I merged all PR and try to make it compile. After that, I found many functions don't work. Even the sync between playing song and playlist broke.

Now I'm in a awkward position. The code in master can compile, but I don't know why daemon communication broke. I don't want to revert all.

**Comment by hasezoey** [comment]
i think the broken communication is because of the merge of the big #154

how does logging work in this library? because from what i can currently tell the current logger in place cannot log to file, making logging bad basically impossible

**Comment by tramhao** [comment]
Logging is implemented mainly on daemon side. As I add logging when I start writing code for daemon. I just forgot a lot of things after 3 months.

**Comment by tramhao** [comment]
I tried to revert the  PR #154 alone but failed. If I have to revert all the way back,can you push again for your PR's? 
Thanks a lot!

**Comment by hasezoey** [comment]
can i try to fix some things? just to note that this may take some time

do you maybe have a discord to discuss?

**Comment by tramhao** [comment]
Sure. My timezone is different East+8 so I don't log into discord often but you can always leave message here and I'll try my best to explain. The code itself is a learning process for me and I'll look into it as well.

**Comment by hasezoey** [comment]
after finishing up my "logging improvements", i have not found anything broken in the communication, could you explain what is not working?

(the status, volume, title, current time / max time, next song all work)

**Comment by tramhao** [comment]
Sure. I found 3 problems mainly:
1. Press n key, in TUI the track changed, but the server doesn't change.
2. Press l key, in TUI the track changed, but the server doen't change.
3. Volume is 70% . I change it to other value and quit, start again the volume revert back to 70% . I suspect all the setting are not saved. Previously the save is in ui/mod.rs. I think remove the commented out lines should fix this.

**Comment by tramhao** [comment]
I compile again the dev branch, and the 3 problems don't exits.

**Comment by hasezoey** [comment]
> Press n key, in TUI the track changed, but the server doesn't change.

true, i was dumb and didnt check correctly

**Comment by hasezoey** [comment]
i think i figured out what the problem is for the next / previous song (but not how to fix, as i am not fully sure about the internals): a notification to the backend is missing (but i dont know why hitting end to next song works)

even though i think i have found the problem, i think the proper solution is to revert the PR's changes for now, and maybe add them later again after some review

**Comment by tramhao** [comment]
I merge it and now it's back to normal. Thanks.
