### ISSUE TITLE
Mpris position not found

### ISSUE THREAD

**Issue by CRAG666** [tramhao/termusic#185]
I'm trying to use mpris to know what minute the current playback is at, but it doesn't work

query 
```bash
playerctl position --format "At position: {{ duration(position) }}"
```

![imagen](https://github.com/tramhao/termusic/assets/34254373/b7d7ae82-e686-4f79-810b-d8898236ca95)

**Comment by hasezoey** [comment]
currently termusic does not support setting the position in mpris, it only reports the length, at least to my knowledge.

see `progress: None`
https://github.com/tramhao/termusic/blob/32f71c47ad1b2656fd0ab49704f8bec683761644/playback/src/mpris.rs#L55
