### ISSUE TITLE
Queue order

### ISSUE THREAD

**Issue by neruthes** [tramhao/termusic#20]
I noticed that, when I add a track into the playlist in queue mode, the new track would appear on the top of the list, and the player will play from top to bottom.

This appears to be counterintuitive. I personally prefer a first-add-first-play pattern. The most recently added track should be played after previously added tracks.

Let me know if you have alternative ideas.

**Comment by tramhao** [comment]
I make the changes in fddc3e936e3d6d5a6f281e73acbec292d019bff6, would you please check if this is ok? Thanks.

**Comment by tramhao** [comment]
Now I've added a switch for this. from v0.6.1.

**Comment by neruthes** [comment]
Thanks. Working well.
