### ISSUE TITLE
Windows: update photo error: Failed to run Ueberzug: program not found

### ISSUE THREAD

**Issue by brian6932** [tramhao/termusic#202]
Ueberzug doesn't even exist on Windows...

This bug's very annoying, happens on any view changes, and requires to hit `esc` each time

**Comment by tramhao** [comment]
termusic utilize third party tool to draw album photo. Ueberzug is the name of the package. On windows, please disable this feature by running `termusic -c`

**Comment by brian6932** [comment]
That's nice, but imo if the feature can't even work on Windows, why not just disable it on compile time

**Comment by tramhao** [comment]
Album photo is nice, but ueberzug author delete the repo. I'm thinking of switching to other method but need to investigate the status of other packages. I'm using Viuer which support kitty image protocol. Under windows, I don't know which terminal is more popular, powershell or cmd?

**Comment by brian6932** [comment]
PowerShell's the more popular shell, people use tons of terminals, with wt (Windows Terminal) likely being the most popular as it's preinstalled.

**Comment by tramhao** [comment]
I built and ran under mingw64 in windows, and album photo is working.

**Comment by brian6932** [comment]
mingw64 is a translation enviornment...
It's not a normal Windows native shell

**Comment by hasezoey** [comment]
Small recap of #229, it does:
- only error once on a permanent error (like ueberzug not being installed) (instead of every time a ueberzug command is tried)
- blanked disable ueberzug for `target_os = "windows"`
