### ISSUE TITLE
Gapless enqueue next changes current songs duration

### ISSUE THREAD

**Issue by hasezoey** [tramhao/termusic#207]
re https://github.com/tramhao/termusic/pull/197#issuecomment-1952794367 https://github.com/tramhao/termusic/pull/197#issuecomment-1952810027

> you just gave me a idea; i think DurationNext was meant to store the duration of the next track while the current one is still playing without changing the total_duration(current playing songs duration).
> but if this is the case, then it is already broken on master, and this PR did not change this behavior, and so will likely need further refactoring to fix. (will open a issue)

> actually broke because of https://github.com/tramhao/termusic/pull/196, i am not fully sure why yet, but will keep investigating

---

the confusion seems to come from there being 3 `total_duration` variables in `rusty_backend/mod.rs`, 2 of which "share" the same name.
before #197, `Play` would set `total_duration(new value in thread)` and set `total_duration_local(Arc-mutex-duration)`, whereas `QueueNext` would set `total_duration(new value in thread)` but NOT `total_duration_local(Arc-mutex-duration)`.
at the time i probably thought they are the same.

**Comment by hasezoey** [comment]
update:
first part of the problem was #196's commit and line [c4f96d59786b3a33482b8d645fb7587536c0ebe0#597](https://github.com/tramhao/termusic/commit/c4f96d59786b3a33482b8d645fb7587536c0ebe0#diff-808b582317c038c19a268d4dcced34210b24948aa6047c43995fdc9670cc6b5cR597), which always set the `total_duration_local(Arc-mutex-duration)` value, which shouldnt happen

second part of the problem was #197's removal of `DurationNext` [165473c34994ad38fca2579b0facce5830ede786#268](https://github.com/tramhao/termusic/commit/165473c34994ad38fca2579b0facce5830ede786#diff-0bcd01f565f47967d749a7f49da9b62c6b773551240455be4654bc102ff2e40cR267-R276), which removed usage of `DurationNext`'s value on next song play

Note that i will try to fix this in a better way (not just limited when `rusty_backend` feature is used), but will not be able to immediately do a pr

**Comment by tramhao** [comment]
Great that you found the cause.
