### ISSUE TITLE
Feature Request: Ability to filter by Genre or by Artist

### ISSUE THREAD

**Issue by drewm1980** [tramhao/termusic#21]
First of all, thanks so much for the free music player! I'm really excited to have a responsive music player after using rhythmbox for years and waiting forever for python to churn through my music library for over a minute on startup.

One thing I miss is the ability to filter my library by tags such as Genre or Artist. Any plans for that, or will navigation stay filesystem based?

Thanks!

**Comment by tramhao** [comment]
I do have a plan to use a database for the library. About the filter, would you please let me know more details like what's the workflow for it? Thanks.

**Comment by tramhao** [comment]
Currently you can search the artist by / . This is actually search for file name, but I always rename song by tageditor, so the filename follows artist-title.ext format.

**Comment by tramhao** [comment]
I'll do this after sqlite database. Seems easier with database for different filtering.

**Comment by tramhao** [comment]
Should be fixed in v0.6.16
