### ISSUE TITLE
not installed when I use cargo install termusic

### ISSUE THREAD

**Issue by jim4067** [tramhao/termusic#22]
I am getting the following errors when I try to install the music player using cargo
![Screenshot_20211127183126](https://user-images.githubusercontent.com/30603522/143687463-d572c850-6973-43a6-8bc7-bc35dbfccbb4.png)

**Comment by tramhao** [comment]
Yes, an upstream upgrade(ytd-rs) break the api compatibility. I'm right now working on branch 0.6, but if you want, you can change the line in Cargo.toml:
ytd-rs = "0.1"
to 
ytd-rs="0.1.5"

and use the old version it should be find. I've handled this api change in branch tui-realm1.0.

**Comment by jim4067** [comment]
I cloned the repo and run it instead locally. thanks 🙏🏾
