### ISSUE TITLE
The app can't initialize properly

### ISSUE THREAD

**Issue by Mxzcabel** [tramhao/termusic#222]
When starting the application I receive the follow output:

```bash
Server process ID: 148438
Error: transport error

Caused by:
    0: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    1: tcp connect error: Cannot assign requested address (os error 99)
    2: Cannot assign requested address (os error 99)
```
My system: Arch Linux
Version: 0.7.11

What should I do? I didn't saw the same or similar issue reported here yet.

**Comment by tramhao** [comment]
I think the reason is tcp port is occupied by other services. Please change the port number in ~/.config/termusic/config.toml

**Comment by hasezoey** [comment]
This issue is currently the case if the TUI cannot connect to the server, likely the server exited somehow before the TUI could connect.
To get the server logs, either start the server directly or use `--log-to-file` and then look in `/tmp/termusic-{tui,server}.log`.

also, are you directly on v0.7.11 or some newer commit? if you are on v0.7.11, please try to use current latest master as there have been many changes since then, but no new version yet

**Comment by Mxzcabel** [comment]
Swapped to another port, but no effect. I couldn't even get `logs-to-file` work with AUR [build](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=termusic). However I compile with cargo following the guide here with standards parameters:
```bash
cargo fmt --all
cargo check --all --features cover,all-backends
```
Then I was able to `--log-to-file`, but no luck, I crashed with the same error above, tried to workaround starting termusic-server first in another port, also nothing changed. 

Below I tried to start `termusic-server` twice to show even with another port I wasn't able to overcome the problem:
```bash
[2024-03-04T10:04:20.859-03:00 ERROR termusic_server]: Error: Error binding address: [::]:50101

Caused by:
    Address already in use (os error 98)

[2024-03-04T10:22:35.319-03:00 ERROR termusic_server]: Error: Error binding address: [::]:50303

Caused by:
    Address already in use (os error 98)
```

**Comment by tramhao** [comment]
you can use lsof command to find an empty port.
```
lsof -i:50101
```

**Comment by Mxzcabel** [comment]
> you can use lsof command to find an empty port.
> 
> ```
> lsof -i:50101
> ```

```bash
COMMAND      PID     USER FD   TYPE  DEVICE SIZE/OFF NODE NAME
termusic- 479375 kvitravn 8u  IPv6 1022517      0t0  TCP *:50101 (LISTEN)
```

**Comment by hasezoey** [comment]
> I couldn't even get log-to-file work with AUR [build](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=termusic).

the AUR build you linked is `termusic`, which is build against a github release (currently v0.7.11), try [`termusic-git`](https://aur.archlinux.org/packages/termusic-git)

> Below I tried to start termusic-server twice to show even with another port I wasn't able to overcome the problem:
> Is there a way to change to type IPv4?

it seems like those ports are already used up. this can happen if different process than termusic is using it, or a termusic version before the current master is used (like v0.7.11) and it crashed, leaving behind a "zombie" process (not fully exiting).
try to kill all termusic-server instances or reboot your system, and try again with the latest master.

PS: ports, to my knowledge, have nothing todo with ipv4 or ipv6 and so changing wont help

**Comment by hasezoey** [comment]
> I intentionally started termusic-serve twice to show different ports but the same outcome.

i read that, maybe thought you maybe tried it twice, where a old "zombie" process was still around

> killing processes or restarting I get empty output when prompt lsof -i:50101 to verify.

if i understand `lsof -i` correctly, empty means nothing uses the port

> It worked when enabling IPv6 again.

i learned something new today

> Any way to redirect on IPv4?

currently `[::]` is hardcoded, will try to make it configurable via config

**Comment by Mxzcabel** [comment]
Thanks for the help and your time. I also learned new things today. You're very thoughtful.
