### ISSUE TITLE
whenever I try to access the root directory it always crashes

### ISSUE THREAD

**Issue by jim4067** [tramhao/termusic#23]
I get this error `thread 'main' has overflowed its stack`

**Comment by tramhao** [comment]
yes, I can confirm this. I'm currently working on branch tui-realm1.0 and will check this problem when I finish the branch. Thanks for the feedback.

**Comment by jim4067** [comment]
your welcome. I think I could also help with adding a help section for the cli before TUI and writing a getting started article.

**Comment by tramhao** [comment]
That'll be great! Looking forward to your PR!

**Comment by tramhao** [comment]
I merge tui-realm1.0 branch into master. And I found it's possible to navigate to root and no overflow now. I haven't debug it but probably it's upstream fix. You could check it out. Probably some small bugs but basically all functions are working.
