### ISSUE TITLE
[Feature] Add search to TUI Podcast Feeds list and Episodes

### ISSUE THREAD

**Issue by hasezoey** [tramhao/termusic#230]
Currently in termusic you seemingly cannot search through the Podcast's `Episodes` list (and maybe even `Podcast Feeds`).
There exists a similar feature in `Library` already which can be activated via `/`.

current termusic is 3560924113989c6a17616ea2143c7f3d79fb87c9

re https://github.com/tramhao/termusic/issues/127#issuecomment-1987376428

**Comment by tramhao** [comment]
Should be fixed by e456540275bc6a7c7579db4db32ee6258301f0de . Please kindly check if there are some bugs.

**Comment by hasezoey** [comment]
at least from my quick testing e456540275bc6a7c7579db4db32ee6258301f0de seems to work great and is exactly what i think the feature should be.

@plum is this the feature and implementation you meant?

**Comment by plum** [comment]
> at least from my quick testing [e456540](https://github.com/tramhao/termusic/commit/e456540275bc6a7c7579db4db32ee6258301f0de) seems to work great and is exactly what i think the feature should be.
> 
> @plum is this the feature and implementation you meant?

Gosh, thanks. I'll check it out. And report back, whatever the case.

Kind Regards,
John

**Comment by plum** [comment]
> at least from my quick testing [e456540](https://github.com/tramhao/termusic/commit/e456540275bc6a7c7579db4db32ee6258301f0de) seems to work great and is exactly what i think the feature should be.
> 
> @plum is this the feature and implementation you meant?

Tested; the search works just as it shol ddo, all functionality there, inlcuding adding to playlist. No hiccups.
Excellent work.

I beleive its an important feature with long lists especially.
Thank you.

John

**Comment by plum** [comment]
Ah, I've found a hitch; Everything seemed to work as it should, until I repeated a podcast episode list  search upon a second (ie. different)  subscription; The episode search window  was popultated with the   list from the preovious subscription searched. 
- This remains the same after closing and restarting termusic in a  new terminal.

John

**Comment by tramhao** [comment]
I checked this. Perhaps I'm doing it wrong. The episode search is among all episodes, not limiting under current selected feed. That's why when you load it, it'll always be the same list. What do you think?

**Comment by plum** [comment]
>The episode search is among all episodes, not limiting under current selected feed. That's why when you load it, it'll always be the same list. What do you think?

Ah! I see. Yes. That's fine then. I had mistaken the re-occuring appearance of a long list from one podcast feed at the top of the seach list.

It's really good, delightful; Very useful.

**Comment by tramhao** [comment]
I'll add a title to show that the episodes are from all feeds.
