### ISSUE TITLE
rusty backend network stream never clear buffer files and grow indefinitely

### ISSUE THREAD

**Issue by hasezoey** [tramhao/termusic#238]
I noticed that when using networks streams, the stream is buffered in a `/tmp` file, but that file keeps growing indefinitely, and after playing ~15 minutes it has grown to ~14Mb, even though it is not seekable (and the stream is not paused).
For context this is a live radio, so it will never end.

i know this is not really significant for this size yet, but still it never gets cleared and for machines which run ~8 hours or even a day, this could quickly grow to gigabytes of unused data.

termusic 07e6a7f971b69368751d57818bb3e4838ad4f6e8

Should we refactor indefinite network streams to not buffer to files and instead use some kind of in-memory buffer? (i am not sure which would be the best, ring buffers maybe?)

**Comment by tramhao** [comment]
I saw that stream-download.rs updated a lot. Perhaps the upstream fix the problem.

**Comment by hasezoey** [comment]
if upstream is [this `stream-download`](https://github.com/aschey/stream-download-rs), then yes, it looks wholly different than our version, but in turn this would also mean completely re-implementing radio download as we patched in our own radio title handling

**Comment by hasezoey** [comment]
just for reference:

```txt
$ ls -al .termusic-stream-cache-GzYcpR
-rw------- 1 hasezoey hasezoey 30664411 Mar 18 16:45 .termusic-stream-cache-GzYcpR
$ ffprobe .termusic-stream-cache-GzYcpR
[mp3 @ 0x63f02a8c3940] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '.termusic-stream-cache-GzYcpR':
  Duration: 00:31:56.53, start: 0.000000, bitrate: 127 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
```

**Comment by tramhao** [comment]
https://github.com/aschey/stream-download-rs/blob/main/examples/from_stream.rs

From the above example, seems that they can parse header now. Maybe we can use them directly, without parsing the header resulted in 2 streams.

**Comment by tramhao** [comment]
I have a working version in dev branch. Would you please check if the problem is solved?

**Comment by hasezoey** [comment]
well, the current dev branch (bd30f74d2e1e63b70c85d106a9021ef1afa7c28f & a84b0c59e414965aeab85824a3c7287ae1dd4f27) *work* but do not fix this problem, there are still 2 streams going.

also i dont quite like how a new tokio runtime is created there, we should likely just pass a handle to the existing one down.

should i give it a try?

**Comment by tramhao** [comment]
I found seeking is not working for podcasts, which used to work. problem.

**Comment by hasezoey** [comment]
> I found seeking is not working for podcasts, which used to work. problem.

is https://github.com/aschey/stream-download-rs/issues/27 related?

**Comment by tramhao** [comment]
No, the problem is the input of symphonia decoder should be mediasource, but stream-download didn't implement this interface(which I implemented before in local stream-download).
