### ISSUE TITLE
search track in playlist

### ISSUE THREAD

**Issue by CRAG666** [tramhao/termusic#24]
First of all, thank you for this excellent software. Now I would like to be able to search for a track in the playlist so that I can reproduce it and that when it finishes the next track is played

**Comment by tramhao** [comment]
Currently there is a similar function in library. You can press `/` key to start search, and after search you can press enter to locate it in the library, or `l` key to load it to playlist. If I implement this similar work flow, is it works for you? Or some modification is needed? Thanks.

**Comment by CRAG666** [comment]
I have already used that function but it is nothing close to what I need, I only need a search engine that searches within the plylist and reproduces what I was looking for. The function that he mentions performs searches within the directory but it is not so useful when you already have a playlist loaded

**Comment by tramhao** [comment]
Please test v0.6.2 and see if it works. When focusing playlist, you can also use `/` key to start the search.

**Comment by CRAG666** [comment]
thanks

**Comment by tramhao** [comment]
I just update the function a little bit but still too early to release a version. Previously the search is based on file name, now it's based on tag information of artist and title. You can checkout master branch to see the result.
