### ISSUE TITLE
podcast start slow and downloaded file is not used

### ISSUE THREAD

**Issue by tramhao** [tramhao/termusic#243]
Podcast start playing very slow, even for downloaded file.

**Comment by hasezoey** [comment]
cannot reproduce on my system or the podcasts that i have for testing.

is this some kind of recent change? if yes, could you maybe bisect and report which commit is the issue?

for reference i use the following feed for testing `https://feeds.megaphone.fm/LMG3928170156`

**Comment by tramhao** [comment]
I think 2 issues are related. 
1. The link in playlist.log is now http thus the server will download instead of reading local file.
2. The buffer size of player is too big?

**Comment by tramhao** [comment]
I cannot add the feed you posted. Error message is :
None
means probably parsing data error. I can open with browser though.

**Comment by hasezoey** [comment]
> I cannot add the feed you posted. Error message is :

how did you try to add it, my way (which i just verified works) is:
- start
- switch to podcasts (via `3`)
- press `s` (to add / search)
- paste (or write) the link
- press enter to add
- wait until it catches up
- done

> The link in playlist.log is now http thus the server will download instead of reading local file.

how did you verify? if i add one from my posted link, it adds it correctly as https: `https://pdst.fm/e/chrt.fm/track/C76EG6/traffic.megaphone.fm/LMG3429682006.mp3?updated=1709970883`

> The buffer size of player is too big?

which buffer, the temporary file storage? (in my case i think it always downloads the full file instead of some chunks, but it still starts before being fully downloaded)

**Comment by tramhao** [comment]
I add the feed same way as you. Perhaps it's network reason. Yesterday at home I cannot add it. Today in office I can.

I don't mean https was changed to http. I mean when http(s or without) were added, the local downloaded file were not used. We can download episodes with d key and listen to it later. It's not the temporary file storage.

**Comment by tramhao** [comment]
I think 2c087b9b7d0821ce628d04a7a47bfdc12a81057d fixed the local file issue.
For the slow start of online episodes, I think it's related to my network. The default search is from apple, and they have a speed limitation of around 1-2M per second. However, with the old implementation of stream-download, the start is still quite fast. 
I remembered you implement a buffer to fix alsa buffer running low issue. Is it related? Or the new stream-download-rs?

**Comment by hasezoey** [comment]
>  I remembered you implement a buffer to fix alsa buffer running low issue. Is it related? Or the new stream-download-rs?

the buffer is used via `BufferedSource`, which is *only* used for `MediaType::Music`, not `Podcast` or `LiveRadio`.
it is maybe related to the change to `stream-download`, as that is the only thing that changed in the time (to my knowledge).

**Comment by tramhao** [comment]
Currently the start speed of rusty backend is still slower than gstreamer and mpv. I think it's ok for now.
