### ISSUE TITLE
Delete one root in config window, but result is not saved.

### ISSUE THREAD

**Issue by tramhao** [tramhao/termusic#245]

**Comment by hasezoey** [comment]
unclear description, is this referring to: deleting a music directory root in the TUI and the config not being saved without that?

but if that is what it is referring to, then i can reproduce it on 18c0f6fe112894dc0bec4602d39fc99d2bfa347a

**Comment by tramhao** [comment]
Yes, sorry I just log the bug. Should be easy to fix. I hope to fix all bugs we find. Maybe we could release 1.0.

**Comment by Mircas001** [comment]
im having the same issue, config window wont save

**Comment by hasezoey** [comment]
@Mircas001 please open a new issue providing what version you use

**Comment by Mircas001** [comment]
nevermind, i did something and it worked
