### ISSUE TITLE
TUI becomes unresponsive if the quit dialog shows up before switching to different tab

### ISSUE THREAD

**Issue by hasezoey** [tramhao/termusic#248]
I just random got into the following situation:
(have quit confirm dialog enabled)
(have a podcast episode as "currently playing")
- started the TUI (+ server)
- pressed q immediately
- TUI loads and shows the "Music" tab
- quit confirm window shows
- the TUI notices a podcast is running and switches to the "Podcast" tab
- the quit confirm window is still open, but nothing has focus anymore and no input is being seemingly handled anymore

last tested on 18c0f6fe112894dc0bec4602d39fc99d2bfa347a

**Comment by tramhao** [comment]
This is because the focus is set to podcast tab, but when popup(quit) showing, keystrokes were sent to popup.
