### ISSUE TITLE
Customize colors

### ISSUE THREAD

**Issue by CRAG666** [tramhao/termusic#25]
First of all it looks spectacular based on termusic except for some elements that look bad (at least in kitty yes). So, like other players of this style, I would like the possibility of creating custom themes. I had thought that the default theme would be the colors of the terminal but that you can add others. Thanks in advance

**Comment by tramhao** [comment]
Yes, I'll do it. Probably in 0.6.3

**Comment by tramhao** [comment]
finished in 0.6.3
