### ISSUE TITLE
integration with playerctl

### ISSUE THREAD

**Issue by CRAG666** [tramhao/termusic#26]
I use playerctl to control music playback but with termusic it doesn't seem to work. My workflow is to use termusic and go to another window in that window if I want to change music I would do it with playerctl but this one did not work. I would like to be able to use playerctl together with termusic

**Comment by tramhao** [comment]
playerctl use mpris to control player. Please build termusic with mpris or simply `make full`. Currently I'm using player-mpris.py( I think it's from a polybar script repo. Supported function: pause, next, previous.

**Comment by tramhao** [comment]
This issue is closed as currently the mpris works.

**Comment by CRAG666** [comment]
@tramhao 
In the termusic metadata, the address of the cover image is not sent
I currently use a bar that shows the metadata of the currently playing song
But the cover image does not appear anywhere
