### ISSUE TITLE
Metadata support for `.opus` files

### ISSUE THREAD

**Issue by hydrobeam** [tramhao/termusic#27]
I've been using `yt-dlp` to download some songs from youtube since I've found the downloading functionality to be a bit slow. I've been getting them in the `.opus` file format and while they play fine, it can look a bit odd without the metadata for the songs. Would it be possible to add support for this file type? 

Also, I've really been enjoying using termusic!

**Comment by tramhao** [comment]
it should be ok to add the support within current structure. Meanwhile, yt-dlp is faster? I'll check it out and probably support using it as well.

**Comment by hydrobeam** [comment]
> it should be ok to add the support within current structure

Thanks!

> Meanwhile, yt-dlp is faster? I'll check it out and probably support using it as well.

Yup, youtube has been throttling downloads and `youtube-dl` has yet to publish a release to handle the issue. `yt-dlp` fixed it two months ago, see this reddit thread for more info:
https://www.reddit.com/r/youtubedl/comments/qfbyal/read_slow_youtube_downloads/

**Comment by tramhao** [comment]
Great! And the wrapper I'm using is ytd-rs, which added support for yt-dlp in recent release. I'll compare it with youtube-dl and see what I can do about it.

**Comment by tramhao** [comment]
In master branch I've implemented yt-dlp. For opus, read meta is ok, but write meta is not working yet.

**Comment by tramhao** [comment]
Now opus file write meta works too. Only thing doesn't work is write photo. Still checking with upstream author.

**Comment by tramhao** [comment]
to use yt-dlp, please use make full or cargo feature gate yt-dlp. It's really fast!

**Comment by tramhao** [comment]
now opus metadata works including album photo. Upstream author of lofty-rs fixed the issue. Please checkout master and compile. Right now I cannot publish it as lofty haven't publish 0.3 on crates.io. Thanks.
