### ISSUE TITLE
Consistent TUI Popup titles (and some text)

### ISSUE THREAD

**Issue by hasezoey** [tramhao/termusic#273]
Currently the TUI has quite the inconsistent titles, some have spacing between the border and title, some dont and some only on one side:
- `-No Spacing-`
- `- Full Spacing -`
- `- Some Spacing-`

This issue is a tracker issue to get the titles consistent.

Also @tramhao, which of the styles should we go for?

**Comment by tramhao** [comment]
2nd looks better to me. What do you think?

**Comment by hasezoey** [comment]
> What do you think?

sure, i personally would be fine with either `No Spacing` or `Full Spacing`, but having it consistent.
