### ISSUE TITLE
The interface doesn't redraw if the terminal size changes

### ISSUE THREAD

**Issue by auronandace** [tramhao/termusic#28]
I'm running i3 window manager and have termusic running in a terminal. If I open anything else that changes the size of the terminal running termusic then the interface gets all glitched.
I think there needs to be a way to detect if the terminal has changed and issue a redraw of the interface.

**Comment by tramhao** [comment]
yes, there is such message.  I'm also using tiling window manager(leftwm). Before I just found the album photo is not redrawing so I just implemented it in master. Would you please let me know the problem you met(a screenshot will be great) or try the version 0.6.4 in master? Right now I cannot publish it in crates.io as a dependency package is not published yet. Thanks.

**Comment by auronandace** [comment]
I just tested 0.6.4 and the issue is fixed. Thanks for such a great project! It is nice to have a rust alternative to cmus.
