### ISSUE TITLE
stuttering when playing flac files.

### ISSUE THREAD

**Issue by HappyGoFishing** [tramhao/termusic#303]
## Environment & Versions

- System:  
OS: ArtixLinux x86_64 (basically archlinux)
Kernel: 6.8.7
wireplumber 0.5.1
pipewire 1:1.0.5

- Termusic version: 

    Termusic d102a05[g]
(using the aur package 0.9.0-1) "termusic"
- Rust version:
rustc 1.77.2 (25ef9e3d8 2024-04-09)

Logs:
No logs were created.

## Description of the Problem

When playing flac files there is a regular stutter that occurs at least once a minute, this happens much less often with mp3 files.

**Comment by tramhao** [comment]
Could be bug in our code for rusty backend. Do you have same problem when using gstreamer or mpv backend? You can switch backend by:
```
termusic -b gstreamer
termusic -b mpv
```

**Comment by tramhao** [comment]
I checked the AUR package doesn't have all backends enabled. If you have time, you can clone this repo and `make full` to do the installation.

**Comment by tramhao** [comment]
You could also upload the file you met problem. I have only very short test file for flac. Thanks.

**Comment by hasezoey** [comment]
also something to consider, is your file on a ssd or spinning disk (or some other slow to react from idle disk)?

**Comment by Emiliasky** [comment]
I'm experiencing the same issue on arch, using the aur package.
Tested with rusty, gstreamer and mpv.
I am using an ssd.

**Comment by HappyGoFishing** [comment]
same

**Comment by hasezoey** [comment]
i do not have any flac-native files, so i can only test on files converted to flac (original mp3 / aac / vorbis), and with those converted files i cannot reproduce this problem on `v0.9.0-367-gbdd32f20[g]` (manjaro linux, pipewire 1.0.7, rusty backend), so more information would be great:
- @Emiliasky what AUR package are you using, `termusic` or `termusic-git` (to my knowledge both only compile backend `rusty` by default)
- could someone maybe provide a flac-native file where they have encountered the problem (could also be send privately)
- debug logs via `RUST_LOG=trace termusic --log-to-file` of when this occurs and then look for the files that are mentioned (message `Logging to file`) (linux default `/tmp/termusic-{server,tui}.log`)

**Comment by HappyGoFishing** [comment]
When I am again using my linux system, I will do more testing and report back here.
