### ISSUE TITLE
Nerd Font Icons doesn't work properly in Kitty terminal(?)

### ISSUE THREAD

**Issue by Opposite34** [tramhao/termusic#327]
I am currently setting up an Arch system and decided on using termusic for my music player. I have installed [ttf-nerd-fonts-symbols](https://archlinux.org/packages/extra/any/ttf-nerd-fonts-symbols/) to work with my font (Fira Code) as Kitty itself [doesn't like when you patch the font directly](https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font). 

Note that I have tried doing the alternative by using the patched fonts provided by this [AUR repo](https://archlinux.org/packages/extra/any/ttf-firacode-nerd/) instead, but neither rendered the icons in termusic properly. 

However, the **nerd font icons rendered fine in other TUIs**. Please see attached image below where I have the GitHub icon (`\uf09b`) and two shuffles (`\uf074` and `\udb81\udc9f`) rendered properly in the Kitty terminal (top left) and neovim (bottom left), while the termusic shuffle / sequential playback mode doesn't work. Also of note that the song I am currently hovering over in the playlist [uses emojis](https://www.youtube.com/watch?v=TM93ntGYLGg), of which it doesn't appear to render as well.

![nerdfont_termusic_problem](https://github.com/tramhao/termusic/assets/54463205/2cc480e6-8ed7-4370-85b8-0983f64863c8)

Some system and version info (in case it is important):
termusic version: 0.9.0-1 (via AUR)
OS: Arch
WM: Hyprland (Wayland)

I would like either a fallback in case Nerd Font breaks (since I can't really see if I'm on shuffle or sequential playback mode) or some fix to this behavior. (EDITED: I have just seen the display symbol toggle in settings. However, this is still quite a weird behavior worthing a report in my opinion.)

**Comment by hasezoey** [comment]
>  termusic version: 0.9.0-1 (via AUR)

please use `termusic --version`, my best guess is AUR `termusic`?

maybe consider trying the latest master, or AUR `termusic-git` (though there have been no known font related updates)

---

the symbols render fine for me (KDE Konsole 24.05.0 + Hack Nerd Font; the same for alacritty 0.13.2), i am not aware of anything we can do to detect if a font display is broken or not.

just to be sure, did you already try restarting your kitty terminal for termusic (or your whole system)?

**Comment by Opposite34** [comment]
> > termusic version: 0.9.0-1 (via AUR)
> 
> please use `termusic --version`, my best guess is AUR `termusic`?

this shows `Termusic d102a05[g]`

> just to be sure, did you already try restarting your kitty terminal for termusic (or your whole system)?

Yep I did so. It seems like some other icons on an unrelated TUI doesn't work as well. If possible can you give me specifically the unicodes for the icons? Just a sanity check in case it is actually on the Nerd Font's part not having everything.

**Comment by hasezoey** [comment]
> If possible can you give me specifically the unicodes for the icons?

https://github.com/tramhao/termusic/blob/f4114102cbb94f28d6357aaedf96db408488f7af/lib/src/config/v1/mod.rs#L75-L77

the missing icons from the track you would need to LS yourself

**Comment by Opposite34** [comment]
Oh my god... I just realized these are not Nerd Fonts... they are emojis....
Installing Noto Fonts fixed my problem. 

Thank you very much for helping me work out the issue.
