### ISSUE TITLE
Full Rust stack

### ISSUE THREAD

**Issue by auronandace** [tramhao/termusic#33]
I've just come across https://github.com/pdeljanov/Symphonia which provides native Rust decoders.

I'm no expert by any means but was wondering if you were aware of this as an alternative to requiring GStreamer. Would be awesome to go full Rust on the audio stack. Would love to hear your thoughts on that project.

**Comment by tramhao** [comment]
It's a great project. Previously I used rodio, but rodio doesn't support seek. I used mpv, but mpv doesn't support m4a, no matter which decoder I installed. I also used vlc, but the library binding for vlc is too limited. Gstreamer is not easy to install in windows. And it's quite bloat. Options are always open to full rust implementation. I'll check it out and see if it's all right for termusic.

**Comment by tramhao** [comment]
closed in v.0.6.7

**Comment by auronandace** [comment]
Thanks for the hard work in implementing a Symphonia backend. You even made it default, which is epic!

**Comment by tramhao** [comment]
My pleasure:)
I like the idea of full rust stack and please kindly test it. Any issues, please let me know:)
