### ISSUE TITLE
No support for `webm`s, doesn't even detect that it can't play them and refuse to play them

### ISSUE THREAD

**Issue by magnus-ISU** [tramhao/termusic#34]
Instead it adds them to the list as 0-duration songs and gets stuck

I thought it wasn't working for a while, as all the music I've downloaded I've stored in `webm`s because they compress the best.

It seems that Symphonia from #33 might fix this, though I don't think it has support for `m4a` so I don't think it is a perfect solution.

`mpv` can play all audio format's I've encountered. Does it's library bindings not provide something that is needed?

**Comment by tramhao** [comment]
termusic use mpv as backend before v0.2.12, but cannot play m4a no matter what codecs I install. webm is quite new to me as it's mainly a video format, right? Need some info about the metadata too.

**Comment by tramhao** [comment]
I searched briefly that gstreamer should support webm. Would you please send me a copy of webm file so that I can try? Thanks.

**Comment by tramhao** [comment]
I tested mpv again and seems m4a is working. Will switch back to mpv a good solution?

**Comment by magnus-ISU** [comment]
> I searched briefly that gstreamer should support webm. Would you please send me a copy of webm file so that I can try? Thanks.

Sure, [here's a link](https://drive.google.com/file/d/1U4eeuFtvhMbOXH5x4_jxESaJXJeiey1r/view?usp=sharing). It might be the case that it doesn't work because there is no metadata on the file. I'm unsure.

> I tested mpv again and seems m4a is working. Will switch back to mpv a good solution?

If you want to do so, though I feel that might be a hassle for you to rewrite the documentation and inform the users. I feel like if you want to be switching back and forth between backends, it would be cooler to try to incorporate Symphonia. But if it isn't a lot of work to switch back to mpv and it supports more than gstreamer, I guess there isn't a good reason not to.

**Comment by tramhao** [comment]
I get a working version in dev branch that uses mpv as backend by default. Webm can be played, but metadata is missing. Meanwhile, gstreamer can play it too.

**Comment by hasezoey** [comment]
this issue will likely be fixed by #205, as for gstreamer and mpv, it seemed to work beforehand already; but still note that mkv, mka and webm metadata will still not be supported

**Comment by hasezoey** [comment]
as a note, #205 has been merged, which makes mkv (and mka) and webm useable in the rusty-backend, but still has some limitations:
- no opus support (opus is 1 of the 2 supported audio codecs for webm spec)
- no metadata support (the UI will display `Unavailable`)
