### ISSUE TITLE
Feature Request: Have search window linger after selecting a song

### ISSUE THREAD

**Issue by hydrobeam** [tramhao/termusic#35]
Hello! When pressing `/` to search for a specific song, the search window closes immediately after picking a song. This makes it a little inconvenient when I want to add multiple songs that match a keyword, or search for multiple songs consecutively. Would it be possible to have the window remain open after picking a song?

I vaguely recall this being the default in previous versions, but I'm not sure.

**Comment by tramhao** [comment]
Yes, it's possible to do it. I'll do it in v0.6.7 because 0.6.6 has too many plans already. Thanks.

**Comment by tramhao** [comment]
Today I fixed it. It'll be in 0.6.6 as the fix is only comment out 3 lines. If you want to try, please checkout dev branch.
