### ISSUE TITLE
Couldn't launch: `The requested address is not valid in its context.`

### ISSUE THREAD

**Issue by Unknown78** [tramhao/termusic#356]
## Environment & Versions

- System: Microsoft Windows 11 Pro for Workstation 64-bit v10.0.22631.3958
- Termusic version: [termusic-v0.9.0-x86_64-windows.zip](https://github.com/tramhao/termusic/releases/tag/v0.9.0)
- Rust version: Nothing installed, just downloaded the binary from the release page.

Logs:
`termusic-tui.log`
```rust
[2024-08-12T15:57:58.021+07:00 INFO termusic]: Waiting until connected
[2024-08-12T15:57:58.026+07:00 ERROR termusic]: Error: transport error

Caused by:
    0: error trying to connect: tcp connect error: The requested address is not valid in its context. (os error 10049)
    1: tcp connect error: The requested address is not valid in its context. (os error 10049)
    2: The requested address is not valid in its context. (os error 10049)
```
## Description of the Problem

I just run `termusic.exe` and it returns error messages.

There are [several issues](https://github.com/tramhao/termusic/issues?q=transport) with the keyword of `transport`, but my specific error is different.

**Comment by tramhao** [comment]
Seems the server is not running. Please try to launch termusic-server.exe and then run termusic.exe.

**Comment by tramhao** [comment]
I just checked that if you unzip the folder, keep termusic.exe and termusic-server.exe in the same folder, the server can be started by client without problem. Maybe you didn't unzip it? Thanks.

**Comment by tramhao** [comment]
maybe you can setup the server port to 127.0.0.1:50101 in config file. The config file is in (C:\Users\Alice\AppData\Roaming\termusic)

**Comment by tramhao** [comment]
Probably the default configuration is not working. I don't know from what time my windows configuration is set as 127.0.0.1 and that's why I can run it but you can't.
