### ISSUE TITLE
Waste of time

### ISSUE THREAD

**Issue by gdonald** [tramhao/termusic#357]
Took me much too long to accidentally discover how any key presses work.  I got lucky and finally saw "Ctrl-h" in a screenshot.  Not sure how you expect anyone to use this with that sort of learning curve.  Wiki page is empty.

So anyway, I press <a>, thinking this is the way to add my directory of mp3s, and nothing happens.

Sad.  Uninstalling.  Good luck with you next victim.

**Comment by gdonald** [comment]
No need to try and help.

**Comment by tramhao** [comment]
Sorry to let you down. Basically I start with mainly vim like hotkeys. If you are not vim user, it will be too much work to configure all key bindings. But if you are from vim, most keys are natural. And all keys can be changed, right in config editor of tui.
