### ISSUE TITLE
[Request] Bump release to `0.9.1` to fix packaging with rust `1.80.0`

### ISSUE THREAD

**Issue by VuiMuich** [tramhao/termusic#358]
It would be nice if you could release a minor bump to `0.9.1` in order to get the `time` crate dep update released for package maintainers (e.g. on nixpkgs).
Of course it is possible to cherry pick the relevant commit and patch packages so they build with rust `1.80.0`, but being able to use the latest release is always nicer :grin:

**Comment by tramhao** [comment]
Sound good to me.

**Comment by VuiMuich** [comment]
Nice, thanks.
So I will change the `nixpkgs` PR to a version update as soon as you have released the version update.

**Comment by tramhao** [comment]
Released V0.9.1, but with some problems https://github.com/tramhao/termusic/issues/259.
Probably you'll need to configure some feature flags in nixpkgs, as the default feature flag for termusic-playback cannot compile. Thanks.

**Comment by VuiMuich** [comment]
It seems to build fine in nixpkgs even without the feature flags, but I get this error in the checkPhase:
```
error: builder for '/nix/store/0afnkjrw4hzfqzi6d7skcds7cfxl16lb-termusic-0.9.1.drv' failed with exit code 101;
       last 10 log lines:
       > ++ cargo test -j 4 --profile release --target x86_64-unknown-linux-gnu --offline -- --test-threads=4
       > warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
       > note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
       > warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
       > note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
       > error: the listed checksum of `/build/termusic-0.9.1-vendor.tar.gz/soundtouch-ffi/src/lib.rs` has changed:
       > expected: 49b1a2fa7698edd0b89328daff83a96284c1874bb1b35a06e17aaf6194b035d0
       > actual:   b367ac09c56ffb5751ee62afbf46ddd23c65adcff8812e702ebc59bc7e44dd6a
       >
       > directory sources are not intended to be edited, if modifications are required then it is recommended that `[patch]` is used with a forked copy of the source
```
This might be a problem of nixpkgs very well, since when skipping the checkPhase the binary seems to run without any issues (just tried playpack of a track and `playerctl next` and `playerctl play-pause`).

**Comment by tramhao** [comment]
I met same warning. I just rename config to config.toml and it is fine. Seems a cargo upgrade caused the warning.

**Comment by tramhao** [comment]
I didn't edit soundtouch-ffi source code. I do reported an issue to this repo, as I cannot build it under windows.

**Comment by VuiMuich** [comment]
There seems to be an issue with vendoring the soundtouch-ffi crate in nixpkgs.
But when I patch the `0.9.1` release with 211fc3fe008932d052d31d3b836e8a80eade3cfe and 211fc3fe008932d052d31d3b836e8a80eade3cfe everything works perfect.
Thanks for everything.

**Comment by tramhao** [comment]
Glad it's working. Thanks for your feedback.
