### ISSUE TITLE
Zellij Unsupported?

### ISSUE THREAD

**Issue by ArctixTheFox** [tramhao/termusic#366]
## Environemnt & Versions
- System: linux nixos 24.05
- Termusic version: 0.9.0

Logs: N/A

## Description of the Problem
It seems that termusic does not support running under zellij.
When using Kitty with Zellij and trying to run termusic, it freezes on:
`Server process ID: 19858`

Enabled logs but no file was ever created.

Starting termusic in Kitty without Zellij seems to work.
Is this a known issue?

**Comment by tramhao** [comment]
I don't have experience using zellij as I use hyprland and it's already tiling. Would you please try to run termusic-server first, then termusic in another window. Thanks.

**Comment by hasezoey** [comment]
> Enabled logs but no file was ever created.

what options did you use? try `RUST_BACKTRACE=1  RUST_LOG=trace termusic --log-to-file`.
or alternatively as tramhao has already suggested run `termusic-server` in its own terminal first and then the command above.

Note: `--log-to-file` only enables logging to the file, it does not change the default verbosity level of `warn`

PS: tmux works perfectly fine

**Comment by ArctixTheFox** [comment]
Apologies for the late reply.

Starting the server first, then the client, resulted in the same behavior as described before.
It does appear the server works fine, the client seems to be the issue here.

I tried to enable logging again, with the rust flags.
It does print that its logging to a file, but the file never ends up being created.
Even tried to change the path of the log file, just in case.
This is the case for both the client as well as the server.

Which leads me to believe that the client freezes up, but never encounters any actual errors.

**Comment by hasezoey** [comment]
>  It does print that its logging to a file, but the file never ends up being created.

which options are you using to start termusic? do you set `RUST_LOGLEVEL=`?

with the same command, does a logfile get created and get written to if you *not* use `Zellij`?

**Comment by ArctixTheFox** [comment]
I did set the Rust log level and used `--log-to-file`

When starting termusic without zellij, the log file gets created _if an error occurs_ which i made sure of by killing the underlying server.

In that case, the log file was created and written to.

If i start termusic within zellij, with the same options as before and kill the server, the client does not quit nor create the log file.

**Comment by hasezoey** [comment]
> When starting termusic without zellij, the log file gets created if an error occurs which i made sure of by killing the underlying server.

> If i start termusic within zellij, with the same options as before and kill the server, the client does not quit nor create the log file.

this is very weird, if you have set `RUST_LOG` at least set to `info`, you should see [`Waiting until connected`](https://github.com/tramhao/termusic/blob/843ac9458135599e5698a77698beffe9b15278b3/tui/src/main.rs#L153C12-L153C35) in the log file and later, if it happens `Connected!` and it should get flushed to the file without having to wait for a error.

in addition, if `--log-to-file` is set, the log file should (to the best of my knowledge) always be created when the logger first initializes (thanks to us [explicitly flushing the logging handle](https://github.com/tramhao/termusic/blob/843ac9458135599e5698a77698beffe9b15278b3/tui/src/logger.rs#L52)), even without anything to write (way before `Server process ID` message)

---

frankly i dont see any reason on why zellij would make termusic behave any different, especially before even switching to the alternate console screen.

did you already try upgrading to termusic `v0.9.1` (which by my version definition is actually a big change compared to `v0.9.0`) and also latest master / compiling it yourself?

also could you provide the full command you are using to test?

**Comment by ArctixTheFox** [comment]
It seems that `v0.9.1` fixed the issue i was having.
Termusic starts up normally now.
Thank you for the help in resolving this
