### ISSUE TITLE
Thoughts on the indicator bar above the playlist section

### ISSUE THREAD

**Issue by neruthes** [tramhao/termusic#37]
I just upgraded to v0.6.5. Now it looks like: `Playlist ──┤ Total 5 songs | 15m 40s | Loop: ⬇ | Add:ﬠ`

- I suggest that "track" is more preferable than "song" since a lot of music tracks are not songs (e.g. orchestra).
- Using "15m 40s" looks a bit overkill; "15:40" should be good enough. When exceeding 1 hour, "1:04:01" will be good. Also, the player progress bar `1m 4s     :     2m 44s` should follow, if we ever change the time format in the indicator bar.
- The symbols after `Add:` are not really intuitive. I had to do experiments to discover what they represented. Using `Add: Next` / `Add: Last` may be better. The specific wording may be open for further discussions. Options include Next/Last, Top/End, Head/Tail, etc.
- Is it possible to use text (instead of icons) for the loop mode indicator? Using "Normal" / "List Loop" / "Single Loop" will be ok.

Also, while vim-style navigation is cool, I would like to have my good old arrow keys back. This is important for me, and I wish you may consider.

**Comment by tramhao** [comment]
arrow keys should be working in library and playlist, I haven't check other parts. Would you please let me know which part it's not working? 

About the title of playlist, I'll make the modification as you suggested and probably have an option to set icons. I just thought the icons are widely used in other players so the meaning should be self explanatory.

**Comment by neruthes** [comment]
> Would you please let me know which part it's not working?

Arrow keys do not work in library and playlist. The only place it works is the quit confirmation dialog.

> probably have an option to set icons

As we gradually have more options, maybe some `$HOME/.config/termusic/config` will be good?

**Comment by tramhao** [comment]
I tested 0.6.5 and the arrow key is not working. I'm changing a lot for hotkey in dev branch. Would you please check out ff210995812ffeb7ea7ef4baf1e8424f43309bf1
? Arrow keys works. For later commits, I'm checking symphonia and not working very well. Thanks.

Right now the config is in ~/.config/termusic/config.toml

**Comment by tramhao** [comment]
I released 0.6.6 but forgot to involve related change. I modified the playlist title and time display format in dev. Please check out latest dev branch to see if it's all right. There is a configuration option: playlist_display_symbol in config.toml, you can set it to false to see texts. You can build with make full.

**Comment by neruthes** [comment]
I just compiled the `dev` branch. The arrow keys are back.

Now the indicator bar looks like `Playlist ──┤ Total 2 tracks | 5:1 | Loop: consume | Add:last`.

For remaining time, I would prefer to have `05:01` instead of `5:1`.

Also, a space should be added between `Add:` and `last`.

The rest are good.

**Comment by neruthes** [comment]
![image](https://user-images.githubusercontent.com/2139261/149769965-2a1ad929-63c8-4b43-a7b7-2e9f2a6b0fdc.png)

Also notice this "Duration" column. Using `01:05` may be better than `1:5`.

**Comment by neruthes** [comment]
![image](https://user-images.githubusercontent.com/2139261/149769965-2a1ad929-63c8-4b43-a7b7-2e9f2a6b0fdc.png)

Also notice this "Duration" column. Using `01:05` may be better than `1:5`.

**Comment by tramhao** [comment]
yes, make sense. I changed in dev and thanks for your advice!

**Comment by neruthes** [comment]
![image](https://user-images.githubusercontent.com/2139261/149884197-12a35ee0-9f9a-43b7-8921-c1a92f6e6bc5.png)

This is from the `dev` branch. Would be better if the padding on both sides are symmetric.

**Comment by neruthes** [comment]
![image](https://user-images.githubusercontent.com/2139261/149887289-9c8fffea-24f5-4c19-82c1-849a2842c9fb.png)

The color here might need some tweaking... Using blue on either the bar or the text may be better.

**Comment by tramhao** [comment]
The duration display format was fixed in dev. For the progress, it's foreground. I change the foreground color default to bright_black. but you'll need to delete config.toml or config it manually in color editor to see the result, as when there is already a value in config.toml, it'll not return back to default. Thanks so much for your feedback!

**Comment by neruthes** [comment]
![image](https://user-images.githubusercontent.com/2139261/150107202-dcfb0f01-7022-43c2-ab36-f16f390d5d8b.png)

LGTM

**Comment by tramhao** [comment]
closed in v0.6.7
