### ISSUE TITLE
Add libsixel as a dependency in Arch Linux PKGBUILD

### ISSUE THREAD

**Issue by HyperWinX** [tramhao/termusic#370]
I installed latest version from official Arch Linux repositories, and got this
![image](https://github.com/user-attachments/assets/02f031b7-0734-47ab-9199-bc1309eec6e6)
Installation of libsixel fixed the issue.

**Comment by tramhao** [comment]
Thanks for your feedback. The PKGBUILD is not made by this project. Would you please feedback to the author?
