### ISSUE TITLE
Some prompts are cut off when the window is too small

### ISSUE THREAD

**Issue by hydrobeam** [tramhao/termusic#38]
When spawning the download prompt with `s`, the exit prompt with `q` or the help prompt, the display is a bit cut off and either hides the text box or some other information. This doesn't hold true for all prompt (`/` search prompt shows up fine). There may also be others that don't show up properly

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/70682032/150135155-945e52e1-64b0-4751-84f8-44ee2edf5b67.png">

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/70682032/150135058-37e64994-e03c-4fc0-abe6-07c2be32f0ac.png">

**Comment by tramhao** [comment]
Thanks for reporting this issue. The problem is that right now the size of dialogue is configured with relative value of the whole terminal window. I'll check on how to set it with fixed value for smaller dialogues.

**Comment by tramhao** [comment]
fixed in dev branch. Please checkout 023a69772c268d5156f7ea98982914a38b220a89 and see if it's ok. Thanks.

**Comment by tramhao** [comment]
now it's in master v0.6.7

**Comment by hydrobeam** [comment]
Fixed, thank you!
