### ISSUE TITLE
Songs don't play and constantly skip to next song

### ISSUE THREAD

**Issue by rypervenche** [tramhao/termusic#4]
Hi there,

I just installed version 0.3.13 via cargo and when I add songs to my playlist they say "Current Playing" and then when I move my cursor it cycles through the songs, constantly skipping the songs that it can't play. I have also tried playing a song that has been downloaded via youtube-dl and it does the same thing.

I have the following packages installed on my machine:

gstreamer
gst-plugins-bad
gst-plugins-base
gst-plugins-good
gst-plugins-ugly

All are version 1.18.4 and 64-bit. I am running Gentoo Linux. Might I be missing a dependency? Is there a good way to troubleshoot this issue?

Any help would be greatly appreciated. This app looks amazing and I can't wait to use it.

Thanks!

**Comment by tramhao** [comment]
seems that the gstreamer is not working. As I'm on arch, maybe some dependencies are not the same with gentoo. I'll list some possible packages:
Build dependencies
lang/rust pkgtools/cwrappers devel/glib2-tools pkgtools/digest devel/pkgconf
Runtime dependencies
multimedia/gst-plugins1-libav meta-pkgs/gstreamer1-default-backend multimedia/gstreamer1 multimedia/gst-plugins1-base multimedia/gst-plugins1-good multimedia/gst-plugins1-bad multimedia/gst-plugins1-ugly multimedia/gstreamer1 multimedia/gst-plugins1-base multimedia/gst-plugins1-good multimedia/gst-plugins1-bad multimedia/gst-plugins1-ugly

**Comment by tramhao** [comment]
the reason for jumping to next song is: when the detected song length is 0, it'll stop playing and play the next song.
for song duration, there are two way to get it. The first is from metadata, and will be showing in queue. The 2nd is from gstreamer, and will be showing in progress bar. So, if these two values are not the same, it means one of them is not correct. The value from gstreamer will be updated to id3 tags of mp3, but if gstreamer is not fully functioning, there will be a problem. 

please also check this plugin: gstreamer-pbutils.

by the way, the rust binding for gstreamer is 0.17.4. Could it be a problem?

**Comment by tramhao** [comment]
I just checked my gstreamer installed:
gstreamer-1.18.5
gst-libav 1.18.5
gst-plugin-pipewire 1:0.3.37
gst-plugin-bad 1.18.5
gst-plugin-bad-libs 1.18.5
gst-plugin-base 1.18.5
gst-plugin-base-libs 1.18.5
gst-plugin-good 1.18.5
gst-plugin-ugly 1.18.5

**Comment by rypervenche** [comment]
Oh! I just realized I didn't have `gst-plugins-meta` installed, which pulls in all of the gstreamer plugins for different codecs. My apologies. It is working now. Thank you for your help!

**Comment by tramhao** [comment]
I'll keep a note for this as the package in gentoo is different.
