### ISSUE TITLE
"Not Support" shows up for some tracks

### ISSUE THREAD

**Issue by m4b** [tramhao/termusic#40]
First off, amazing cli tool, I _love_ it.

I see "Not Support" show up for some tracks; reading them with crate id3 shows no errors, and the track title and artist can be extracted/displayed normally.

![Screenshot from 2022-02-13 21-48-09](https://user-images.githubusercontent.com/1920204/153807287-b36fc03a-22c9-4b34-b840-2397ea1c102d.png)

**Comment by tramhao** [comment]
Firstly, thanks for your feedback. Seems wired as the metadata getting from lofty is working well for me with mp3 file. Would you please send me the mp3 file with error? Thanks.

**Comment by tramhao** [comment]
Now I filtered the file extension, so unsupported files will not be added to playlist.
