### ISSUE TITLE
Feature Request: Increase/decrease speed

### ISSUE THREAD

**Issue by danrobi11** [tramhao/termusic#47]
Unless there's already an option and I havent seen it?

**Comment by tramhao** [comment]
There is no function for this but I saw it in several apps especailly for books. I'll add it to the plan. Thanks.

**Comment by tramhao** [comment]
please kindly check out 4c0c1337bd3aaa1bdf691eb15159f178e806de55. I tested symphonia backend with mp3 files and it works. Thanks.

**Comment by danrobi11** [comment]
@tramhao Im not a dev, it doesnt mean much to me. Sry :/ 

I could always compile it. Im not sure which branch tho. Good to know it works on your end. Very nice :+1:

**Comment by tramhao** [comment]
The dev branch is ok to checkout. And if it's ok, I'll include it in next release.

**Comment by tramhao** [comment]
After you git clone dev branch, you could use git checkout 4c0c133 to get the right commit. Thanks.

**Comment by danrobi11** [comment]
Sry, something does not let me compile. When can call it here since it works for you. 

```
$ make
cargo fmt --all
error: no such subcommand: `fmt`

	Did you mean `fix`?
make: *** [Makefile:6: fmt] Error 101
```

**Comment by Serial-ATA** [comment]
@danrobi11 You need to install rustfmt: `rustup component add rustfmt` (If you're using rustup)

**Comment by danrobi11** [comment]
Doesnt work with `make release`

```
cargo build --release
error: failed to parse manifest at `/home/danrobi/termusic/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
make: *** [Makefile:14: release] Error 101`
```

I've tried installing rustup and rustfmt, im on debian based distro and thats what I get:

```
Error: rustup not found
Error: rustfmt not found
```

**Comment by tramhao** [comment]
Seems the rust toolchain in your system is old. Did you install from repo before? If so, don't worry, I'll include this feature in new version and hope you can get the update from your repo.

**Comment by danrobi11** [comment]
> Did you install from repo before?

Yep must be. Tbh, I dont recall installing it. Must be long time ago.

**Comment by Serial-ATA** [comment]
Just to let you know, rust 2021 was released in 1.56.0. Looks like Debian stable is still on 1.48.0 (https://packages.qa.debian.org/r/rustc.html).

**Comment by danrobi11** [comment]
@Serial-ATA 

> Looks like Debian stable is still on 1.48.0

Yep. Thank's for the link. Now that I know the package is named `rustc`: 

Package: rustc
Version: 1.48.0+dfsg1-2
State: installed
Automatically installed: yes

**Comment by danrobi11** [comment]
Running the new v0.6.14 here. Increase/decrease speed working perfectly. Awesome :+1:  Thank you much! @tramhao 

Closing
