### ISSUE TITLE
Branch structure

### ISSUE THREAD

**Issue by Serial-ATA** [tramhao/termusic#48]
Rather than have a `dev` branch, could you make a `stable` branch and use `master` instead? Since github defaults to `master` when making a PR, it would make it easier to not have to think about it.

Either that, or could you write up a `CONTRIBUTING.md` that makes it clear you should be targeting the `dev` branch?

**Comment by tramhao** [comment]
The dev branch is very unstable, and sometimes I have to commit to it even compile failed. As long as things are all right, I'll merge into master branch. So generally speaking, PR to master branch is no problem and I'll make modification if dev branch is inconsistent. I'll write it in contributing.md. Thanks.

**Comment by Serial-ATA** [comment]
Ah, I didn't think about that workflow. Thanks for clarifying :)
