### ISSUE TITLE
Search in folder

### ISSUE THREAD

**Issue by orhun** [tramhao/termusic#5]
Hello! I just tried `termusic` and it works flawlessly, thank you for this awesome project.

I have a pretty big mp3 archive and one functionality that I couldn't find on `termusic` is "search in folder". Is it currently possible to do that? I'm sorry if there's a key binding that I overlooked.

So far I tried `s` but that seems like only for searching on YouTube. I think pressing `/` and searching in the folder (left menu) would be pretty sweet. I can also work on an implementation and submit a PR if this is a missing feature.

**Comment by tramhao** [comment]
I haven't done that and will add it to the tasks.

**Comment by tramhao** [comment]
done it in 696430e116cc19e8f88e1a8ae5f6d4e05099afc5. Please kindly check if it's working for you and if you could submit a PR it'll be great!

**Comment by orhun** [comment]
It works pretty good. Thank you!
