### ISSUE TITLE
Can't fastforward paused songs in v0.6.11

### ISSUE THREAD

**Issue by hydrobeam** [tramhao/termusic#53]
In `v0.6.7`, you could fastforward a paused song, but in `v0.6.11`, this is not possible.

https://user-images.githubusercontent.com/70682032/158039272-b704e1f1-5536-4c42-93a6-a2128e79b149.mp4

The above is not possible under `v0.6.11`. Also, not really related, but I noticed that the rate at which the song is fastforwarded with `f` is slower in the latest version.

Tested under the gstreamer backend, in alacritty.

**Comment by tramhao** [comment]
About the forward, it's slower in new release. It's probably related to the recent change to modification of song duration judgement. I'll try to find the reason.

**Comment by tramhao** [comment]
fixed in v0.6.15
