### ISSUE TITLE
Search prompt colouring looks a little off

### ISSUE THREAD

**Issue by hydrobeam** [tramhao/termusic#54]
After pressing `/` to pull up a search prompt, I noticed that it looks a little bad with the grey colouring, it would make more sense to just use the same black background all around imo. This also might just be something to do with my terminal (alacritty), I'm not sure.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/70682032/158039399-b3f0b124-7aaa-4d35-b477-969debb94b27.png">

**Comment by tramhao** [comment]
It's my fault. I didn't set the color scheme for dialogues. I should set them with the foreground and background color from config. Will fix it in dev branch.

**Comment by tramhao** [comment]
fixed in dev branch ff07b150bd297d26f70d6202573ab78a537a60c4. 
If you can compile it, you can try it now. Otherwise, you can wait for next release. Probably 1 week later. Thanks.
