### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by FlanOfHarmony** [tramhao/termusic#55]
Hi,

It seems there has been some changes to the player back-end, it can play next song faster than before which is great!
However, I'm experimenting a few annoying bugs :

- If I play a playlist, pause the song and leave the player untouched, it suddenly plays and skips to the next song after tens of minutes
- I haven't found out the conditions to replicate the issue, but sometimes if I quit termusic in a particular way and then launch it again, all playlist are broken: if I play a playlist, first song gets played, but next song in playlist doesn't play. Doesn't matter if it's loop mode or not.
- If I play a folder which contains music along with the album art (in .jpg or any image format), the player tries to play the image (despite indicating it doesn't support it) and crashes. Especially annoying in random mode.
- Thank you for enabling custom shortcut! However, it seems the search menu (accessed with "/") still uses the default shortcut and not the ones in config.toml…)

Keep up the good work!

**Comment by tramhao** [comment]
Yes, I just met with several issues you mentioned. I'll debug them one by one. Thanks for reporting!

**Comment by tramhao** [comment]
> * If I play a playlist, pause the song and leave the player untouched, it suddenly plays and skips to the next song after tens of minutes

This bug should be identical to https://github.com/tramhao/termusic/issues/56 . And should be fixed in https://github.com/tramhao/termusic/commit/64e443450d0cb8fdbd6746b187ef37d9b4618f0c of dev branch. Thanks.

**Comment by tramhao** [comment]
> * Thank you for enabling custom shortcut! However, it seems the search menu (accessed with "/") still uses the default shortcut and not the ones in config.toml…)

This I checked the program and code, and it works without problems. Would you please let me know, which key you're using for search function and doesn't work? I suspect it's a capital letter. And in this case you'll need to select shift in key configuration window. Thanks.

**Comment by tramhao** [comment]
> > * Thank you for enabling custom shortcut! However, it seems the search menu (accessed with "/") still uses the default shortcut and not the ones in config.toml…)
> 
> This I checked the program and code, and it works without problems. Would you please let me know, which key you're using for search function and doesn't work? I suspect it's a capital letter. And in this case you'll need to select shift in key configuration window. Thanks.

For example, if I use a key 'a', it's a combination of none+a in key configuration(bring up by shift +K). If I use key 'A', it's a combination of shift+'A'.  A combination of none+'A' or shift+'a' will not work.

Thanks.

**Comment by tramhao** [comment]
> * I haven't found out the conditions to replicate the issue, but sometimes if I quit termusic in a particular way and then launch it again, all playlist are broken: if I play a playlist, first song gets played, but next song in playlist doesn't play. Doesn't matter if it's loop mode or not.

For this issue, I think it's probably related to file format. In previous version, I didn't filter the file format, but after  https://github.com/tramhao/termusic/commit/74fd4a0ea146cdafac0e39fb1f80b1498d8ec280 , the file extension is filtered before adding to playlist. So probably this issue could be fixed too. Please kindly try and thanks so much for your feedback.

**Comment by tramhao** [comment]
Above fixes are all in 0.6.12 . Please kindly try it.

**Comment by FlanOfHarmony** [comment]
Hi! Sorry for the long delay!
I just tried v0.6.12 It seems that the first three bugs are corrected (though I'll may have to try some more to be sure about the quit and relauch issue). Thanks.
As for the shortcut issue, I might have been unclear: the search menu itself (and not the shortcut to open it) still used the default shortcuts and not the one defined. However it looks like this is almost fixed, except for the play song shortcut and play folder shortcut (in the rest of the interface they're correctly mapped to the keys I've assigned but they are still mapped to "l" and "L" in th search menu).

**Comment by FlanOfHarmony** [comment]
The play shortcut in search menu is indeed fixed in this release. However I've still encountered the broken playlist (next song refusing to play). Can't figure out the conditions for it to happen, but last time I've noticed the time progression bar was broken too.

**Comment by tramhao** [comment]
I'll rewrite the code of auto play, as my new feature of changing playback speed break auto play completely.

**Comment by FlanOfHarmony** [comment]
Using the latest version for a while, and I haven't met the last issue that last issue that remained, so I suppose you rewrote the code of auto play to correct that last issue.

**Comment by tramhao** [comment]
yes. When implement gapless playback, related code was changed dramatically, so this issue could be closed. If you meet any problems, please open new issues and thanks for the feedback.
