### ISSUE TITLE
Time keeps going when on pause

### ISSUE THREAD

**Issue by teackot** [tramhao/termusic#56]
If you put a track on pause it stops playing, time bar stops moving, but time actually keeps going without the track and Termusic skips to the next track when time runs out

**Comment by tramhao** [comment]
Thanks so much! I'll fix it today.

**Comment by tramhao** [comment]
Harder to fix than I thought, so I'll try it tomorrow. Thanks.

**Comment by tramhao** [comment]
Should be fixed in 64e443450d0cb8fdbd6746b187ef37d9b4618f0c of dev branch. Thanks.

**Comment by tramhao** [comment]
Please try this commit: 70c8388a0661b0e6a4fe943171170c5b15fb2bba . Thanks so much for your testing and report!

**Comment by teackot** [comment]
Sorry for the delay. Still no 😕. I'm on the latest dev commit

**Comment by tramhao** [comment]
I checked with v0.6.12, and the pause works for me without the wrong calculation. Would you please try it? Thanks.
