### ISSUE TITLE
[Feature request] Don't remove the song from the playlist once played

### ISSUE THREAD

**Issue by lcheylus** [tramhao/termusic#58]
Hi, thanks for your work : termusic a great CLI tool to play my MP3 songs on Linux.

When a track from a playlist was played, it is removed from the displayed playlist. I wish an option to keep the played songs displayed in the current playlist : useful when the list contains all songs of an album.

**Comment by tramhao** [comment]
This can be done by switching the playback mode to playlist. Please press `m` key when focusing playlist. Thanks.

**Comment by lcheylus** [comment]
I don't understand (or there is a bug) toggle for loop mode (key `m` in playlist) : 

1. First mode : when a track from a playlist was played => removed from the playlist : OK
2. Loop mode : when a track was played => put in last position : OK (loop mode)
3. Third mode (unamed ? don't understand the icon) : in this mode, the first song of my playlist is played on loop. Same result if I try to play next song (key `n`) => current song restart from the beginning. If I move with key on the 2nd song and press `l` to play, first and second songs are swapped.

**Comment by tramhao** [comment]
the third mod is single loop. it will replay the first song until you change to other songs manually.

**Comment by tramhao** [comment]
This is consider fixed. Thanks.

**Comment by lcheylus** [comment]
Sorry, but I consider my request not closed : there is no mode to keep the songs displayed in the playlist once it has been played.

**Comment by michaelkirk** [comment]
If you need an example, the ncmpc+mpd media player behaves the way @icheylus is describing. They have an option, called "consume mode", that behaves similar to how termusic behaves now, but with consume mode disabled, the songs stay in your playlist after you've played them. Your "current song" is highlighted in the playlist as you listen.

A couple of use cases: you can go back and easily start an album over, or just see your progress through it. You can see the title of the song that just finished. etc.

**Comment by tramhao** [comment]
> If you need an example, the ncmpc+mpd media player behaves the way @lcheylus is describing. They have an option, called "consume mode", that behaves similar to how termusic behaves now, but with consume mode disabled, the songs stay in your playlist after you've played them. Your "current song" is highlighted in the playlist as you listen.
> 
> A couple of use cases: you can go back and easily start an album over, or just see your progress through it. You can see the title of the song that just finished. etc.

Personally I use  loop mode more. Do you think it's ok? Thanks for your heads up and I will check ncmpcpp for how to handle the palylist.

**Comment by michaelkirk** [comment]
I usually don't like "loop" mode, I get annoyed when I realize I'm half-way through accidentally re-listening to an album.

I think different people want and expect different things with this feature, but "non-consumable" playlists are a pretty common behavior across media players that support playlists (e.g. ncmpc, vlc, itunes)

Here's a screen recording of VLC so it's clear what I mean:
https://user-images.githubusercontent.com/217057/167955567-e3d58dd4-a3d8-4f4b-a28f-6f0376ce70c0.mp4

With termusic you can't go back and re-play a song in the playlist.

**Comment by tramhao** [comment]
I'm working on a branch with sqlite support, with database, the playlist will be redesigned. Playlist will be save to database, and can be reopen, and will not be deleted. Currently the playlist is more like a playing queue.
