### ISSUE TITLE
[Feature] Display cover if JPG/PNG file present in folder

### ISSUE THREAD

**Issue by lcheylus** [tramhao/termusic#59]
I organize my albums as follows : one directory per album with all the tracks and a JPG/PNG file for cover (named `cover.{jpg,png}`)

I'm using Kitty as terminal : cover is displayed properly if ID3 tag (APIC) is present. But I would like the cover to be displayed in terminal if JPG/PNG file is present in the directory with a specific name : `cover.jpg` or `front.jpg`.

**Comment by tramhao** [comment]
currently only the image embeded into each track is displayed. Your idea seems like album photo. I have a question, which image will be displayed if both the jpg/png file and the id3 tag are available? Thanks for the feedback.

**Comment by lcheylus** [comment]
Yes, my proposal is to display album photo/cover.

If jpg/png file and ID3 tag are available, priority to ID3 tag => could be more specific with different images for each track.

**Comment by tramhao** [comment]
Please check out this commit and see if it's ok. 7ee9a8bb62dee2bca8aa991d7d7c2442a6b09e28 . Thanks.

**Comment by lcheylus** [comment]
Build and tests OK with this commit : 
- unsupported types (PNG/JPG) not displayed in playlist when I add a folder (album).
- PNG/JPG file for cover is displayed if present in folder.
- if APIC ID3 tag is present for a track, displayed in terminal.

Thanks.

=> closed.
