### ISSUE TITLE
Arrow keys don't work during search

### ISSUE THREAD

**Issue by auronandace** [tramhao/termusic#60]
Termusic 0.6.12 - default Symphonia backend on alacritty 0.10.1.

When in the library you can press `/` to initiate search mode. I start typing to narrow down the list. Press tab to swap to the pane below the search bar. In the results box the arrow keys used to work for going up and down. Now only the vim search keys `k` and `j` seem to work.

**Comment by tramhao** [comment]
Thanks for reporting and I'll fix it.

**Comment by tramhao** [comment]
It's fixed in dev branch commit: b6550cc7d6473d51489c7e714b668cc0a10fef29. Please kindly check. Thanks.

**Comment by auronandace** [comment]
Tested. Arrows work as expected in the search mode. Thanks for the fix. I'll let you close the issue on your next bugfix release.
