### ISSUE TITLE
Feature request: Allow Left arrow key when the cursor is not at a directory

### ISSUE THREAD

**Issue by neruthes** [tramhao/termusic#61]
![image](https://user-images.githubusercontent.com/2139261/161679151-4ccd4c0f-20a6-441f-8416-3e1db0d96feb.png)

Take this for example. When the cursor is here, I hope that hitting the Left arrow key may collapse the current directory.

Current version: `b29aacb322daa680b57e54c155ab3f6971f81c71`

**Comment by tramhao** [comment]
Good idea. I'll do it. Thanks for your feedback:)

**Comment by tramhao** [comment]
Please try this commit in dev branch: cb0601cb50e9ed8966b994f63b770899504be81d.
After commit, I found another issue, what if the selected node is a closed folder? Should the focus go to upper dir as well?

**Comment by neruthes** [comment]
> Should the focus go to upper dir as well?

I think we should move the focus to the parent, but do not collapse the parent directory.

This may also apply to other cases, so that the Left Arrow key is explained as two clauses:

- Try collapsing the currently focused node.
- If the node is not a directory or is already collapsed, move the focus to the parent node.

**Comment by tramhao** [comment]
I understand now. Please check dev branch commit b6550cc7d6473d51489c7e714b668cc0a10fef29. Thanks.

**Comment by neruthes** [comment]
lgtm
