### ISSUE TITLE
Feature request: One more level of expandable hierarchy

### ISSUE THREAD

**Issue by neruthes** [tramhao/termusic#62]
![image](https://user-images.githubusercontent.com/2139261/161679396-b80e1b08-ea51-4a7d-af5c-77bf2e333503.png)

I have a `library/artist/album/[disc]/track` hierarchy structure (the disc level is optional), and I have a shell alias `ttermusic` for `termusic $MYMUSICLIB`, so that I may access my music library in a simple manner.

However, I cannot expand the disc directory. I wish one more level may be allowed. Thanks.

**Comment by tramhao** [comment]
Yes, this could be done. However, in currently status, you can also use enter and backspace to step into and out of directory structure.

**Comment by tramhao** [comment]
Please kindly checkout this commit in dev branch. f595c739f772bffc4b6b59a29dce0a0b723ed31a

**Comment by neruthes** [comment]
lgtm
