### ISSUE TITLE
Alsa Crash on 0.6.13

### ISSUE THREAD

**Issue by levone1** [tramhao/termusic#65]
Just installed 0.6.13, and getting a crash...

`ALSA lib conf.c:3817:(config_file_open) cannot access file /etc/alsa/conf.d/50-arcam-av-ctl.conf
ALSA lib conf.c:3737:(snd_config_hooks_call) function snd_config_hook_load returned error: No such file or directory
ALSA lib conf.c:4201:(snd_config_update_r) hooks failed, removing configuration
ALSA lib conf.c:3817:(config_file_open) cannot access file /etc/alsa/conf.d/50-arcam-av-ctl.conf
ALSA lib conf.c:3737:(snd_config_hooks_call) function snd_config_hook_load returned error: No such file or directory
ALSA lib conf.c:4201:(snd_config_update_r) hooks failed, removing configuration
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DefaultStreamConfigError(DeviceNotAvailable)', src/player/rusty_backend/mod.rs:42:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`
Tried with 'cargo install' and build from source. Also tried as root and non-root. Same message every time.

Last time I installed was v0.6.3, and worked fine.

Could be just me and my niche situation (running SailfishOS on mobile), but figured I'd report in case it helps something.

Thanks

**Comment by tramhao** [comment]
I think it's related to symphonia backend. As in v0.6.3, it's still gstreamer backend. For quick fix, you can build with make gst && make post. For real fix, it's related to alsa playback. Seems configuration file is missing. Thanks.

**Comment by levone1** [comment]
Update - found all plugins in CentOS repo and working now... Thanks
![Screenshot_20220420_001](https://user-images.githubusercontent.com/43003405/164288395-e54c54b1-32fe-4f32-9201-01d731da41ae.png)
