### ISSUE TITLE
Feature Request: Any plans for discord rpc?

### ISSUE THREAD

**Issue by Vaimer9** [tramhao/termusic#67]
It would be very cool to have a discord rpc feature like spotify has where it shows your current song and such. Will this feature ever be considered?

**Comment by tramhao** [comment]
would you please let me know what it looks like? sounds interesting.

**Comment by Vaimer9** [comment]
I think you'll know what [discord](https://discord.com) is, for some reason spotify rpc does not work for me, so here is an image from another user
![image](https://user-images.githubusercontent.com/81609819/164912218-7ac50879-820d-49aa-8531-d0ffa3be90e6.png)
I have blurred their handles to keep their privacy

**Comment by tramhao** [comment]
looks like mpris. So basically what I need to do is to broadcast the meat information of playing tracks. I think it is good to have. I will add it to the plan.

**Comment by Vaimer9** [comment]
Here's a helpful library! https://crates.io/crates/discord-rich-presence/0.1.2, I've also used this library in a project of mine, p useful

**Comment by Serial-ATA** [comment]
Just to let you know, only Spotify is able to do dynamic images, so you'll need a single asset to show.

**Comment by tramhao** [comment]
I found another lib here https://lib.rs/crates/discord-sdk.

You mean only spotify can display dynamic images like gif?

**Comment by Vaimer9** [comment]
@Serial-ATA Yeah images are impossible, you would have to manually add each cover into the application. But the other metadata seems useful enough

**Comment by Serial-ATA** [comment]
> I found another lib here [lib.rs/crates/discord-sdk](https://lib.rs/crates/discord-sdk).
> 
> You mean only spotify can display dynamic images like gif?

By dynamic I mean changing it to the covers of songs. You have to upload your pictures to Discord for it to be used, so you can't change it. It's a weird system.

**Comment by Serial-ATA** [comment]
> @Serial-ATA Yeah images are impossible, you would have to manually add each image into the application. But the other metadata seems useful enough

Yeah I totally agree, I've used https://github.com/justas-d/mpd-rich-presence-discord personally. It's nice to have :)

**Comment by Vaimer9** [comment]
> > @Serial-ATA Yeah images are impossible, you would have to manually add each image into the application. But the other metadata seems useful enough
> 
> Yeah I totally agree, I've used https://github.com/justas-d/mpd-rich-presence-discord personally. It's nice to have :)

yeah I had exactly this in mind

**Comment by tramhao** [comment]
Please check out this commit in dev branch: 527471f1d8135ea9eb5269296b80613e32a20e98.
It's works on my side. Any suggestion is great!

**Comment by tramhao** [comment]
This commit solved the panic problem. Please check it out: 12fa5c9d0691048c6ee7547ec0a4d46f42fbcf1a

**Comment by Vaimer9** [comment]
@tramhao works just as intended! Although a nitpick but the art rlly doesn't fit that well 😅. No offense if you made this art tho.

**Comment by Vaimer9** [comment]
also, pausing the song should make the presence stop

**Comment by tramhao** [comment]
By the way, I figured out that there are two ways to show the timestamp, one is elapsed and the other is remaining. Which one is prefered? Thanks.

**Comment by Vaimer9** [comment]
elapsed time sounds better

**Comment by tramhao** [comment]
Thanks for the feedback and commit 096587096c732b0a47e32f1ef34fa9c9ea269f49 in dev branch seems all right.

There is still one issue though. If the playback speed is adjusted, the elapsed time in discord will be different from termusic progress bar. It's very hard to fix as in discord, it's only a timestamp, no other settings available.

**Comment by tramhao** [comment]
This issue was fixed.
