### ISSUE TITLE
Optionally hide non-audio regular files whose basenames start with dot

### ISSUE THREAD

**Issue by neruthes** [tramhao/termusic#68]
![image](https://user-images.githubusercontent.com/2139261/166098493-9bbef87c-6360-4bd3-921e-619ebf7f44f2.png)

I have been developing something and I need "hidden" files which should not disturb daily listening.

So I think it would be nice if I can hide such files which satisfy the following criteria:

- It is located at the root of the library directory.
- It is a regular file (not a directory or symlink or fifo).
- It is not an audio file (tell by `file` command or extension name).

Such files may be safely hidden from library listing...

**Comment by tramhao** [comment]
Thanks for your feedback. I think it's good to have this feature. I'll check it today.

**Comment by tramhao** [comment]
Please checkout commit 05f6c4feaf42888dc9cb4a221f85e5f0d6a58fae in dev branch. I simply ignore all hidden file or folder. Is it ok? Thanks.

**Comment by neruthes** [comment]
lgtm
