### ISSUE TITLE
Running on WSL2

### ISSUE THREAD

**Issue by pcause** [tramhao/termusic#69]
I am trying to run on WSL2 a fedora based WSL.  I can build and run on regular Fedora but when I build on WSL2 and run it crashes.  I am not a rust person and suspect I have some library or another missing.

here is the trace:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DefaultStreamConfigError(BackendSpecific { err: BackendSpecificError { description: "ALSA function 'snd_pcm_open' failed with error 'EHOSTDOWN: Host is down'" } })', /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/termusic-0.6.14/src/player/rusty_backend/mod.rs:43:60
stack backtrace:
   0:     0x55cfac213c5c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2afed960fc1b4464
   1:     0x55cfac23c42c - core::fmt::write::h597fbc5aa1ac45ee
   2:     0x55cfac20b705 - std::io::Write::write_fmt::h9493c50d61a85999
   3:     0x55cfac215910 - std::panicking::default_hook::{{closure}}::hd30bc046ab258a36
   4:     0x55cfac2154c9 - std::panicking::default_hook::hb9f1eb191641bdc9
   5:     0x55cfac215f46 - std::panicking::rust_panic_with_hook::hb9d236646af55711
   6:     0x55cfac215ca0 - std::panicking::begin_panic_handler::{{closure}}::h14434cbcabaa4cba
   7:     0x55cfac2140f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h26bd53be421671f5
   8:     0x55cfac215a09 - rust_begin_unwind
   9:     0x55cfabbdba81 - core::panicking::panic_fmt::hdf3d63a0638a18f3
  10:     0x55cfabbdbb73 - core::result::unwrap_failed::h132b9db788875a4e
  11:     0x55cfabd556d8 - <termusic::player::rusty_backend::Player as core::default::Default>::default::h37f49b59e7511f90
  12:     0x55cfabdce601 - termusic::ui::model::Model::new::h12e450339ab25a7a
  13:     0x55cfabc9f00c - termusic::main::h8a55c2b45683c9b2
  14:     0x55cfabc3ce33 - std::sys_common::backtrace::__rust_begin_short_backtrace::h26b057470a65730f
  15:     0x55cfabca6929 - std::rt::lang_start::{{closure}}::h613a3cd97dfe15ed
  16:     0x55cfac21345e - std::rt::lang_start_internal::hd168ff9bff1c33a1
  17:     0x55cfabc9f272 - main
  18:     0x7f82e4159590 - __libc_start_call_main
  19:     0x7f82e4159649 - __libc_start_main_alias_2
  20:     0x55cfabbdc1f5 - _start
  21:                0x0 - <unknown>

Using Fedora 36 Beta in WSL2 but also using Fedora 36 on a standalone system and all works.  Any idea??  I can run cmus just fine.

**Comment by tramhao** [comment]
Seems alsa is not working on your system.  Please try two solutions:
1. Install alsa and alsa dev package.
2. switch to mpv or gstreamer backend.

**Comment by pcause** [comment]
I had the alsa packages.  Added rsut-alsa stuff and the alsa-plugins-pusleaudio that turned the trick.
