### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by YuFong** [tramhao/termusic#7]
The following warnings were emitted during compilation:

warning: `"pkg-config" "--libs" "--cflags" "gstreamer-player-1.0" "gstreamer-player-1.0 >= 1.12"` did not exit successfully: exit status: 1

error: failed to run custom build command for `gstreamer-player-sys v0.17.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install6qnBPi/release/build/gstreamer-player-sys-050699e367bffae5/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GSTREAMER_PLAYER_1.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`"pkg-config" "--libs" "--cflags" "gstreamer-player-1.0" "gstreamer-player-1.0 >= 1.12"` did not exit successfully: exit status: 1
  --- stderr
  Package gstreamer-player-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-player-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-player-1.0' found
  Package gstreamer-player-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-player-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-player-1.0' found

warning: build failed, waiting for other jobs to finish...
error: failed to compile `termusic v0.3.13`, intermediate artifacts can be found at `/tmp/cargo-install6qnBPi`

Caused by:
  build failed

**Comment by tramhao** [comment]
seems you don't have gstreamer-player installed. Which distribution are you using? Please check the related packages.

**Comment by YuFong** [comment]
the err have been solved.

pc env: Ubuntu 20.04 LTS
 
After install GStreamer libs, then it works.
-----------------------------------------------------------------------
Install GStreamer on Ubuntu or Debian
Run the following command:
apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
