### ISSUE TITLE
key to stop/cancel song that is playing

### ISSUE THREAD

**Issue by pcause** [tramhao/termusic#71]
I start playing a song but how do I get it to stop?  Don't see a key to do that in help.  Once started not in the playlist box.  Sorry if I missed it

**Comment by tramhao** [comment]
Pause by space, but the player doesn't really have a stop status, as long as there are tracks in playlist.

**Comment by pcause** [comment]
If there is noting in the playlist and one song playing there ought to be a way to kill the song.  If I use n when there are songs in the playlist, you stop the playing song and go to next, right?  What about the del key to kill current song.  If there are more songs in playlist, go to next otherwise you are in the state where yoiu'd be if playlist emptied.

**Comment by pcause** [comment]
perfect.

**Comment by pcause** [comment]
looks good.  be interesting to try.  i am not a rust dev.  I know there is a way you can label stuff so us novices can pull the latest with cargo and try.  short of that, I will wait for a release to test

**Comment by tramhao** [comment]
Don't worry. I just released v0.6.15, with several important bug fixes. Thanks.

**Comment by pcause** [comment]
thanks.  tried aand things seemed to work.
