### ISSUE TITLE
[feature request] reorder playlist

### ISSUE THREAD

**Issue by pcause** [tramhao/termusic#72]
If one if focused on the playlist pane, have an ability to move a song up/down in the playlist

**Comment by pcause** [comment]
i think people add items and then might decide to change what is in what order because of mood.   most other players allow for this.

**Comment by tramhao** [comment]
Yes, I agree. Multi selection is very hard but I can do something like yank and paste, to adjust the order of one track. What do you think? Thanks.

**Comment by pcause** [comment]
that's good.  also for one selected item move up/down a single position would, I think, be good enough.  just leave cursor on the item so after you move up/down you can repeat.

**Comment by tramhao** [comment]
good idea. I'll do as your suggested.

**Comment by tramhao** [comment]
Please checkout commit 3eca96f272579885ec577fc7ae2f2368b873ef32 in dev branch. ctrl+j and ctrl+k to move track down and up. shift is better but shift k is taken by key editor. I don't want to change existing keys too often. Thanks.

**Comment by pcause** [comment]
looks good.  waiting for a release to really try

**Comment by lxcode** [comment]
Moving a track individually is good for a more or less randomized playlist, but if you want to move an album to the front of the playlist, the ability to select multiple tracks and then yank/paste would be pretty helpful.

**Comment by tramhao** [comment]
The default hotkey of swap up/down are changed to shift + J and shift + K in v0.7.0. Thanks.
