### ISSUE TITLE
Shows "status running" even when paused

### ISSUE THREAD

**Issue by michaelkirk** [tramhao/termusic#73]
<img width="518" alt="Screen Shot 2022-05-06 at 8 40 20 AM" src="https://user-images.githubusercontent.com/217057/167166277-af37abfb-219b-4191-a66e-ef5890b47a16.png">

It used to say: `Playing: Kyo Ichinose - Blue Grains` it now says `Status: Running`, even when paused. 

- I liked having the song title somewhere there, but maybe you had a good reason for removing it.
- "Running" is kind of strange terminology. Maybe "Playing" would be more conventional.
- I was expecting it to update to "Paused" when I hit `space` to pause.

**Comment by tramhao** [comment]
I move the song title to lyric title because it's too long thus the volume and speed is not showing sometimes. I'll check why it's not correctly showing the status.

**Comment by tramhao** [comment]
Please check commit 6de9ae2dbcc0df62efeb2414a6ba74fc7a969dcf in dev branch. Thanks.

**Comment by tramhao** [comment]
released v0.6.15, and all bug fixes are included. Please try it. Thanks for reporting the issue.

**Comment by michaelkirk** [comment]
Running/Paused now works - thank you!
