### ISSUE TITLE
[Feature request] Support for xspf playlists

### ISSUE THREAD

**Issue by pcause** [tramhao/termusic#75]
it would be great to be able to select an xspf playlist file and have the music specified in the file loaded into the playlist pane of termusic.  This is a portable format and the spec is [here](https://www.xspf.org/)

**Comment by tramhao** [comment]
Seems quite nice. I'll check and see how to do it. The bigger issue perhaps is that currently the playlist have 3 different modes: consume, loop and repeat 1 track only. With xspf playlists, perhaps it's better not to alter the content, so consume mode is not ok. Also, right now in loop mode, the currently playing song will be added to the end of playlist, and such modification is not good for saved xspf also. 
I think I need to change the processing of playlist. 
Thanks for feedback:)

**Comment by tramhao** [comment]
I understood now. And this should be not hard to do.

**Comment by tramhao** [comment]
I found a lib https://lib.rs/crates/playlist-decoder which support xspf, m3u and more!

**Comment by tramhao** [comment]
I have a commit in dev branch: 82234734bc0510c1e93b27355a169fd2ad0ee394.

It uses playlist-decoder and works with my hand-written m3u. But I tested with xspf saved by vlc and didn't work. Do you have xspf files so that I can test? Thanks.

**Comment by pcause** [comment]
I have several xsfp files. Note that an xsfp can be full path or relative/short version.  So /home/you/somedir/somemusic.mp3 or if in  the entry is somemusic.mp3 and we are in directory /home/users/Music the file is expected to be in the directory.  This second form makes the xspf file portable and rides with the music it is stored with.

**Comment by pcause** [comment]
aqgree.  order is important.  people order some playlists for a mood or because a flow seems right so them

**Comment by tramhao** [comment]
I finished the order fix in dev branch commit 6ab12806481c6feb3960694ff8357634e01a7e41.
Please try if it works with your playlists, and if there are any problems, please let me know. Thanks!

**Comment by pcause** [comment]
just figured out how to use cargo to pull/build from a branch.  the new playlist support added one of mine and started playing.  But now I want that "delete" item from playlist pane even more,  LOL

**Comment by tramhao** [comment]
Please elaborate:) You mean edit the playlist of other formats?

**Comment by pcause** [comment]
no, just deleting itms from the playlist panel.  if 5 titles are there i might want to remove one from that panel not from the directory or from within a playlist file.  Just from the panel.   Delete in the file list means delete the file.  delete in the playlist panel means remove from the list of songs to be played.  I can re-add by selected in file list and hitting "l".

I remember there was some implementation issue with this.  If you can't easily delete perhaps you can add a "flag" for each item in the play list panel to "skip".  When that item is would be about to be played, if skip is set, skip and then play next file.

**Comment by tramhao** [comment]
This can be down with d key when focusing playlist panel. This will not modify the playlist loaded.

**Comment by tramhao** [comment]
fixed.
