### ISSUE TITLE
6.16 - seems to hang if music directory is sshfs mounted

### ISSUE THREAD

**Issue by pcause** [tramhao/termusic#77]
My Music directory is mounted with ssfs.  Whwn I start termusic it seems to hang.

**Comment by tramhao** [comment]
I'll have to test, but what will happen in your situation, if you mount sshfs in one place, and symlink it under music dir?

**Comment by tramhao** [comment]
I tested with two methods:
1. mount remote mp3 folder in $HOME/mp3 and start termusic, it works normally.
2. mount remote mp3 folder under $HOME/Music/mp3 and it works as well.

The remote folder is in my local network.

Perhaps your music directory is very far away?

**Comment by pcause** [comment]
> I tested with two methods:
> 
>     1. mount remote mp3 folder in $HOME/mp3 and start termusic, it works normally.
> 
>     2. mount remote mp3 folder under $HOME/Music/mp3 and it works as well.
> 
> 
> The remote folder is in my local network.
> 
> Perhaps your music directory is very far away?

My music folder is on my local network.  cmus starts quickly using this same mount.    Mine is mounted as ~/Music but i also created another directoty xxx and tried.  same.  added a sub-directory yyy under xxx and mounted there and same hang.  I am using fedora 36.  

I have an Ubuntu system and will try there later to see if there is a difference

**Comment by tramhao** [comment]
Please check v0.7.0. It support several root folders. Please set a local folder first and switch to the sshfs mounted folder with `o` key.

**Comment by pcause** [comment]
Tried this.  When I switch seems to hang.  I let sit for over 30 seconds.  I think there is some issue with the way you are reading the directory list.  Even when I select a local directory with my music startup takes 10+ seconds.  as an example, cmus gets a directory list in a second or two.  so perhaps whatever you are doing to get the list is slow on normal and looks like a hang on sshfs mounted directory

**Comment by tramhao** [comment]
Perhaps it's because I'm syncing the database when program start. In my local testing, my root folder contains only about 400 tracks and seems all right. You can try with a new command line parameter `--max-depth 2` or 3 to compare the speed.

**Comment by tramhao** [comment]
I tried to disable sync_database, and it's quite fast to start. If you have more than 1000 tracks, I believe there will be a significant difference.
I'll try to make the database running on a separate thread. Still checking how to do it.

**Comment by tramhao** [comment]
I have an improved version in dev branch: 12803a1eabb1373c44c4dffa4ce1aab385341102 
This can improve the 2nd time loading greatly.
Please check and see if the speed is all right. Thanks.

**Comment by tramhao** [comment]
Please try this commit in dev branch: e67fcb3009d09792a2bd37790343c3de9eb70d04 .
It runs sync_database in the background thread, so the loading speed is faster, especially for big collections.

**Comment by pcause** [comment]
no a rust expert,  what is the cargo line to do this

cargo install --git https://github.com/tramhao/termusic ??????

what do i use after the git argument

**Comment by pcause** [comment]
figured it out.  built.  no real difference

**Comment by tramhao** [comment]
To ensure it works:
1. clone the repo to your computer:
`
git clone https://github.com/tramhao/termusic.git
`
2. enter the termusic direcotry, and run following commands:
`
git checkout dev
make && make full
`

This way the program will be copied to `~/.local/share/cargo/bin/` . Please run it from there.

By the way, may I know how many tracks are in your music root? I need a similar folder to test the reason for slow loading.

**Comment by pcause** [comment]
rebuilt and tested again and this time worked!

**Comment by tramhao** [comment]
Have you met problem with this build? 
I met several times that when I open, and tried to add some random tracks, and the program freeze. Have to close the whole terminal. Seem to me some conflict between background thread and search database.

**Comment by tramhao** [comment]
I figured out the problem. When I delete something in music folder, the database sync will hang there. It's because I use same connection twice without close it. It's fixed in latest dev.

**Comment by tramhao** [comment]
fixed.
