### ISSUE TITLE
Music files must be put into ~/Music?

### ISSUE THREAD

**Issue by c02y** [tramhao/termusic#8]
I don't know whether you have tested it or not.

I move my music files into another folder such as `/tmp` or `~/test/`, you can load those music files into the ui of termusic but they won't be played by termusic.

They are only playable when they are inside the `~/Music` or subdirectory inside `~/Music`

**Comment by tramhao** [comment]
You can change the directory in ~/.config/termusic/config.toml .

**Comment by c02y** [comment]
I notice that I can `termusic /path/random/dir` that contains music files, termusic can load them into its ui but unable to play it.

And I have to fix the `music_dir` value? Both sound unreasonable.

**Comment by tramhao** [comment]
termusic command line options can get from termusic --help

**Comment by c02y** [comment]
![image](https://user-images.githubusercontent.com/2135996/134694968-f1a280cc-99c2-4867-8ae4-fbabdbbad735.png)

**Comment by tramhao** [comment]
And for the music files, you don't need to copy it around. For example, I have my music files in a folder synced by verysync, among several machine and my mobile phones. Then I put a symlink under my ~/Music.

**Comment by tramhao** [comment]
Yes, just -h and -v. I tried to eliminate unnecessary dependencies and because I don't have too many options, so I parse it by myself.

**Comment by tramhao** [comment]
flac should be supported by gstreamer. If not, please install gstreamer libs. There are several related libs stated in readme.

**Comment by c02y** [comment]
> And for the music files, you don't need to copy it around. For example, I have my music files in a folder synced by verysync, among several machine and my mobile phones. Then I put a symlink under my ~/Music.

Normally I put my music files in `~/Music`, but when I try to file issues of termusic, I try to simplify the structures of the music file/directory, so I copied a file and a lyric file into another directory and found the fixed `music_dir` issue.

fixed `music_dir` is unreasonable, don't know why you made this decision since I never saw that a music/video/pdf/image opener needs its user to put the targets into the specific path, `termusic music_file` or `termusic music_dir` should be possible and the music files should be playable right away, currently you can load it but you cannot play it.

> flac should be supported by gstreamer. If not, please install gstreamer libs. There are several related libs stated in readme.

flac files are playable by termusic once they are inside `~/Music`, it is not a gstreamer or any dependency issue.

**Comment by tramhao** [comment]
this should be a bug. It's supposed to be playable for any folder. Let me check it.

**Comment by tramhao** [comment]
fixed in d56a21f8363f5c63a3b8f4cfac9aa1ba04fdab4d
