### ISSUE TITLE
[Feature request] Shortcut to change directory as root for Library

### ISSUE THREAD

**Issue by lcheylus** [tramhao/termusic#81]
Hi,

I would like to have a shortcut (`o` for **Open** could be a good candidate) to choose a directory as new root for Library. 

For now, I have to navigate with Backspace/Enter to change root directory between `~/Music/` (local directory for my albums) and `/mnt/disk/Music/` (NFS directory mounted from my NAS).

**Comment by tramhao** [comment]
Hello and thanks for your request. Do you mean after press o, we should open a dialogue to choose a directory? I haven't check but dialogue is not easy to implement in TUI.

For me, I have a folder synced with all my machines and is mounted as ~/Sync/mp3, I symlink this folder to ~/Music thus I don't need to change root. I think you could do similar things for your NFS mounted directory.

**Comment by lcheylus** [comment]
Yes, I would like to have a shortcut (`o` for Open) to choose a directory, not necessarily using a dialogue.

Indeed, I could symlink my NFS share for Music with my local Music folder. But I could also want to open another directory for root folder to find songs or albums.

**Comment by tramhao** [comment]
For your second purpose, you can use `termusic ~/tmp` to open any folder. By the way, if you've opened a folder once, the tracks will be added to database, even it's not under root directory. For the open command, I'll check how to do it. Thanks.

**Comment by tramhao** [comment]
I just thought of a way to finish this. I'll configure root_dir as several folders separated by `;` . After pressing `o` key, you can switch among them.

**Comment by tramhao** [comment]
I have a working version in dev branch commit 9b1810b864b7a25fde7be9f33d88b17ff9a454f4 .
You can use `o` key to switch root folders. You can also use `a` key to add a folder to root folder lists. use `A` to remove a folder from root folder lists.

**Comment by tramhao** [comment]
It's now in v0.7.0. Please check if this function suite your need. Thanks.

**Comment by tramhao** [comment]
This issue is fixed. If you meet any problems, please don't hesitate to reopen it or open a new issue. Thanks.
