### ISSUE TITLE
Feature request: ability to populate playlist with x random tracks or albums

### ISSUE THREAD

**Issue by lxcode** [tramhao/termusic#83]
This would be equivalent to the tqueue / lqueue functions of cmus — my usual cmus workflow (which I'd love to replace with termusic) is to append 50 or so random albums to the playlist, remove or reorder a few of them and let it play.

Alternatively, a way to just append a single random album to the playlist would be good enough.

https://man.archlinux.org/man/cmus.1.en

**Comment by tramhao** [comment]
This should be not hard to do. I'll check cmus first. Thanks for the idea.

**Comment by tramhao** [comment]
Do you have some preference of keyboard hotkey? Thanks.

**Comment by lxcode** [comment]
For hotkey, how about T to add a random track or A to add a random album, while on the playlist? Both could default to 1.

For selecting album, I think using the metadata is best, but to avoid confusion it should probably be attempted like:

* Albumartist + album name
* If that fails, artist + album name

This would manage the cases of multiple artists using the same name for an album, as well as compilation albums (e.g. various artists).

**Comment by tramhao** [comment]
T key is currently used for switching lyrics. Capital a is not used, but `a` is used to switch add queue position. I'd rather use a combination of `s`  for selecting tracks and `S` for selecting albums. Currently `s` is used for randomize playlist, I could change it to `r`. How about that?

**Comment by tramhao** [comment]
About the quantity, I saw in cmus that they're both default to 1. But I think selecting 1 track is quite limited. I want to set tqueue quantity default to 20, which will be similar to real albums. What do you think?

**Comment by tramhao** [comment]
I have a working version in dev branch commit 705a13c607611cfe02930d19ef08028b0013eb6e. If you could compile, please check if this function suit your need. Please focus playlist and press `s` and `S` for tqueue and lqueue. Thanks.

**Comment by lxcode** [comment]
No problem with 20, and I have no strong opinion on the keybindings, s and S work fine. I just tested the dev branch and can confirm it works as expected, with compilation albums as well. Thanks!

The only thing I noted is that it will treat any tracks that don't have metadata as being one big album, with "Unsupported?" as the artist, due to that being the default in track.rs:172.

**Comment by tramhao** [comment]
Yes, and probably we should ignore those tracks without album.

**Comment by tramhao** [comment]
I've update the dev branch commit 81ba8bdb1b7f57a7eaf17ae5f2666e0abe985bef. 
Actually I'm now only using the album name to filter it. For artists, I haven't thought of the implementation. Thanks.

**Comment by tramhao** [comment]
Released in v0.7.0. Closing this issue. If you meet any problem, please don't hesitate to reopen it. Thanks.

**Comment by lxcode** [comment]
Minor issue here: current implementation goes by album name instead of artist-album when queueing a random album, which results in things like this:

<img width="529" alt="image" src="https://user-images.githubusercontent.com/1959603/203783490-40c2bc9d-dfdb-478a-a343-7cfa4c27f237.png">

**Comment by lxcode** [comment]
Minor issue: the current implementation goes by album name instead of artist-album when queueing a random album, which can result in this kind of output:

![image](https://user-images.githubusercontent.com/1959603/203783705-cd82e2e1-e2e4-4de9-926d-61f631d968c8.png)

when you have separate albums with the same name.
