### ISSUE TITLE
[BUG] main panicked because of "sending on a closed channel" on `v0.6.17`

### ISSUE THREAD

**Issue by TD-Sky** [tramhao/termusic#85]
Every time termusic finish playing one song, it would panick with:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-1`,
 right: `8`', $HOME/.cargo/registry/src/mirrors.bfsu.edu.cn-4c6e9dcaa6bd74e7/cpal-0.13.5/src/host/alsa/mod.rs:132:9
Error is: sending on a closed channel
```
How to fix this problem ?

**Comment by tramhao** [comment]
Is this problem happened when you turn of gapless mode? 
I just fixed a bug regarding symphonia backend and gapless mode this morning in dev branch: 705a13c607611cfe02930d19ef08028b0013eb6e .
Thanks.

**Comment by tramhao** [comment]
I'll release this bug fix today in v0.6.18. Please kindly try. Thanks.

**Comment by tramhao** [comment]
released.

**Comment by TD-Sky** [comment]
This bug has been fixed.
