### ISSUE TITLE
[feature request]: Enable features via command-line arguments

### ISSUE THREAD

**Issue by lm41** [tramhao/termusic#87]
I prefer to have a fully compiled version where I can keep the features on, or off, through arguments. Sometimes I need termusic without album art, but sometimes with. this is the same with the discord rpc. It would be a lot easier if it could be disabled/enabled via the arguments.

**Comment by tramhao** [comment]
You mean you want to disable some options at running time. It make sense. I need to think about the best way to do it.

**Comment by tramhao** [comment]
I have a working version in dev branch commit: 4fa47bf6566e27cdd27a96eab14e630cbcf68fab .
Please check if it's ok. Any improvements are welcome:)

**Comment by tramhao** [comment]
released in v0.7.0
