### ISSUE TITLE
Cannot find local lyrics

### ISSUE THREAD

**Issue by c02y** [tramhao/termusic#9]
![image](https://user-images.githubusercontent.com/2135996/134624190-781acc81-2baa-41f1-910c-257fc20a2168.png)

**Comment by tramhao** [comment]
yes currently only the lyric embeded will be loaded. You can check the lyric online in tageditor by press t key. Then you can embed it into the flac file.

**Comment by c02y** [comment]
OK.

**Comment by tramhao** [comment]
The cover is already in the file. The problem is, I only find kitty terminal support display of images with good resolution. For other terminals, sixel library can gave a very blury image. Please try it in kitty. Thanks.

**Comment by c02y** [comment]
I'm using Kitty.

**Comment by tramhao** [comment]
I am using zsh and no tmux. let me check fish and tmux. probably tmux will not work.
