### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by CRAG666** [tramhao/termusic#92]
![Screenshot from 2022-10-18 at 13_00_27 828105390](https://user-images.githubusercontent.com/34254373/196708454-2d598df3-5152-426e-9fd1-2e60c3d04710.png)
Everything works normal until, the photos of the songs begin to be changed and then pauses and does not let any action, I have to use Kill to close.In the end I get the error I show in the photograph

**Comment by tramhao** [comment]
Would you please delete all files in /tmp folder and see if it works?

**Comment by tramhao** [comment]
The app will save cover to cache dir and read it from there. Seems in your system the cache dir is not available, for me it's ~/.cache So the app use /tmp dir as a fallback. However, there are too many files in tmp dir so the error happened. 
I change the code in master branch, and use ~/.cache/termusic or /tmp/termusic folder for saving the album cover photo. It should be fine.

**Comment by tramhao** [comment]
It's in 02964e8910a636862721fc34ae582d4c24417c73. You can check out master code to compile. Thanks.

**Comment by tramhao** [comment]
Seems you're using kitty. Please try with alacritty and see if it works.

**Comment by tramhao** [comment]
seem like a bug from a package viuer. I changed my part and wait for the upstream to fix it. Thanks.
