### ISSUE TITLE
Save playback position

### ISSUE THREAD

**Issue by Ondra-Kavan** [tramhao/termusic#94]
Would it be possible to add an option to save position on close? MPV supports it so it should be possible but I'm not entirely sure.
It would be useful when listening to audiobooks.

**Comment by tramhao** [comment]
yes, it's possible. It need add a position value to database, and this value will be the last played position for each track.

**Comment by tramhao** [comment]
Finished in v0.7.6 . Please check if it's working in your situation.

**Comment by tramhao** [comment]
improved in v0.7.7. Now the current track is saved and restart app will continue from last position.
