### ISSUE TITLE
download failed: Error download: failed to execute youtube-dl

### ISSUE THREAD

**Issue by NEsanya** [tramhao/termusic#95]
When i trying to download a song from youtube i get error. I have installed yt-dlp, ffmpeg, gstreamer, mpv. Im using pipewire.

OS: arch linux (zen 6.0.10)
terminal: alacritty (also tryed in tty)

**Comment by tramhao** [comment]
I checked today and download is working. Please run the following:
```
yt-dlp "https://www.youtube.com/watch?v=jlh1TIn0294"
```

**Comment by tramhao** [comment]
I mean run the command in your terminal, and see what happens.

**Comment by NEsanya** [comment]
Sorry, my bad. It's workes only in a choosen directory (it would be nice if program will show message like "Failed to download x. Please, choose directory to download") 

By the way, the player really nice :D

**Comment by tramhao** [comment]
The root folder will be chosen when you start termusic. Do you mean that you don't have ~/Music folder? I'm thinking how to avoid this error. Thanks for yoru feedback!

**Comment by Mawfyy** [comment]
i have the same error, some help?
