### ISSUE TITLE
Reconsider the use of Ctrl+C as keyboard shortcut

### ISSUE THREAD

**Issue by neruthes** [tramhao/termusic#99]
Conventionally, Ctrl+C means SIGINT. Rare exceptions include GNU nano, where Ctrl+C means getting info about current cursor location.

Also, version 0.7.7 (local build, 443f8a66b680948577fa1f711131d54cd6323b74) doesn't seem to be handling this keyboard shortcut correctly.

Using Ctrl+C is unconventional and creates extra debugging labor. Probably changing to another shortcut will be better. Options include Shift+C and Alt+C.

![image](https://user-images.githubusercontent.com/2139261/209292541-db253467-8edf-4a6d-9cae-ee5d65be37e3.png)

Environment: bash, i3wm, alacritty, X11.

**Comment by tramhao** [comment]
Thanks and I'll modify it. 
Shortcuts need more adjustments. Your suggestion is very helpful!

**Comment by tramhao** [comment]
Default key binding of config editor changed to shift+c in v0.7.7. released.
